### ISSUE TITLE
Fatal error: Call to a member function stdWrap() on string in TSFEUtility.php

### ISSUE THREAD

**Issue by ericstumper** [clickstorm/cs_seo#1]
Hi,

I just installed cs_seo on a TYPO3 7.6.9 and as soon as I open up the options of any page I get a fatal error:

```
Fatal error: Call to a member function stdWrap() on string in /Applications/MAMP/htdocs/typo3_gny/www/typo3conf/ext/cs_seo/Classes/Utility/TSFEUtility.php on line 88
```

I inserted a var_dump in the `getPageTitleSeparator` function and got an empty string back from `$GLOBALS['TSFE']->cObj`. What could be the problem here?

Edit: I used the published TER version 1.1.0, not the development branch.

Thanks in advance.

**Comment by mhirdes** [comment]
Hi,

please include the TypoScript of the extension. At the moment this is required to get the final Link in the preview wizard.

That should solve the problem.

**Comment by ericstumper** [comment]
Thanks for your help, this indeed solved the issue. The TYPO3 extension documentation site wasn't reachable yesterday, otherwise I would have seen that I had to include the TypoScript from your installation instructions...

**Comment by mhirdes** [comment]
No problem. You're welcome.
