### ISSUE TITLE
[FEATURE] Set Page Keyword Focus

### ISSUE THREAD

**Issue by thegrbteam** [clickstorm/cs_seo#10]
On the page properties SEO tab, to add a field where you enter your focus keyword for the page. This has a count that confirms the keyword/phrase has appeared in the Title, Description and page content.

**Comment by mhirdes** [comment]
We will do this.

**Comment by thegrbteam** [comment]
Excellent, it will be a really useful feature and help the extension become more of an analysis tool as well as administration.

Thank you.

**Comment by thegrbteam** [comment]
I was wondering if you had any rough timeline for this feature? The reason I ask is we're about to carry out this work over about 700 pages for a large website updated. I thought if it's coming soon it's worth waiting for, if not we'll just get started. Thanks

**Comment by mhirdes** [comment]
Today I will start with the work.

**Comment by thegrbteam** [comment]
Great news, happy to test and feedback.

**Comment by mhirdes** [comment]
Hey,

so I created a new branch https://github.com/clickstorm/cs_seo/tree/evaluation . This is still under development. I check amongst other things when the focus keyword is set, if it appears in the browser title, the meta description and the content. Do you miss something?

You can test the dev Version. Clear all caches and make a DB update.  There is a new Extbase-CommandController-Task in the scheduler to evaluate all pages. Because currenty I use curl to fetch the HTML it could take some minutes to evaluate all pages.

Tomorrow I will continue developing, e.g. to catch the pages_language_overlays etc. 

Kind regards.

**Comment by thegrbteam** [comment]
Hi, sounds great, we'll be testing it today. When you say make a DB update, do you just mean update the current extension or is this another step we should be taking to try the new dev copy?

**Comment by mhirdes** [comment]
I mean that after you pull the branch, you have to go to the database anylizer to update the database structure. Only a new table to save the scores will be inserted. So the current metadata will not be changed.

**Comment by mhirdes** [comment]
Hey @thegrbteam, did you test it already?

**Comment by thegrbteam** [comment]
I wasn't totally sure on the safest way to add this new dev version so I'm waiting to hear back from our developer so he can do it. My concern was if I remove the current one to add this new one then it might delete the table with all our meta data in (over 500 pages worth). Would that be the case? We will be picking this up Monday now.

**Comment by mhirdes** [comment]
No, no fields will be deleted, only new fields will be added.

**Comment by thegrbteam** [comment]
We're trying to add it but it seems to break it. At the moment we're renaming the old one to cs_seo_old and uploading the new one. Then we deactivate and reactivate cs_seo but it gives an error:

TYPO3 Fatal Error: Extension key "cs_seo_old" is NOT loaded! 
It's a line in the ExtensionManagementUtility.php

This was how our developer thought it was done. The easiest way to update the db was to deactivate and reactivate... but obviously not. Sorry about this.

So it's safe to delete the current version we have of cs_seo, upload the new dev copy, then run the db analyser and we won't lose anything?

**Comment by mhirdes** [comment]
Yes this is safe. Of course you can reinstall the current version after you did the test. The database analyzer asks you what fields and tables you want to add. It also asks which fields and tables you would like to delete, if  there are some. But he wont ask to delete sth. because only new field will be added.

**Comment by mhirdes** [comment]
You also can make a database dump if you want 100% to be sure.

**Comment by thegrbteam** [comment]
Seems we have issues with accessing the install tool section where the analyser is, permissions problem I'm guessing. I'll update you when the devs have looked.

**Comment by jayprakashyug** [comment]
We are developing for thegrbteam who made this feature request. 

We have added the version of cs_seo and the keyword focus field has appeared. 

There is no counter though as described above in this thread where is tells us how many times and and where the keyword appears. Where is this counter supposed to appear?

**Comment by mhirdes** [comment]
Hi,

please update to the latest commit. The evalutaion is shown in the page module (maybe you have to update the extension manager configurations of the extension) and also in the SEO module. Bevore you see any update you have to press the Update button. 
![cs_seo_typo3_page_analysis](https://cloud.githubusercontent.com/assets/915162/18088109/fd04b12e-6eb8-11e6-8815-c8824f0f5e38.png)

**Comment by mhirdes** [comment]
New main version 1.6.0 is available on TER. Maybe you can test this now.

**Comment by jayprakashyug** [comment]
Thank you mhirdes,

i will check it today.

**Comment by thegrbteam** [comment]
Hi there,
I've tried the new keyword featured today, and it still doesn't seem to work. have tried across many pages too. Have attached screenshots of one example.

![image](https://cloud.githubusercontent.com/assets/20797868/18125464/4b9dd332-6f6e-11e6-8701-a7a2a805b786.png)
![image](https://cloud.githubusercontent.com/assets/20797868/18125478/59719854-6f6e-11e6-8baf-dac46e59370c.png)
![image](https://cloud.githubusercontent.com/assets/20797868/18125485/5ebb74c4-6f6e-11e6-9567-60eb041ecea2.png)

**Comment by mhirdes** [comment]
Did you update the database? The page must also be available in fronted. If the cache is off it could take some time that a page is analysed.

**Comment by thegrbteam** [comment]
Yes we updated the DB and the page is available in the front end. Cache is on too. The keyword is set, we click update, it does the little animation and then still says no results.

**Comment by mhirdes** [comment]
I really would like to help you, but without an error message or anything I can't. Is the backend URL the same as the Frontend, also https:// and http://. Otherwise maybe you could send me a temporarily access.

**Comment by mhirdes** [comment]
Have you set a domain record in the root page?

**Comment by thegrbteam** [comment]
Much appreciated. Could you provide your email and I'll get you temporary access.

On 1 Sep 2016, at 15:38, mhirdes <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you set a domain record in the root page?

-

**Comment by mhirdes** [comment]
Sure: hirdes@clickstorm.de

**Comment by thegrbteam** [comment]
Hi, just checking you got access ok and if you have any news for us?

**Comment by thegrbteam** [comment]
Hi, is there an issue? Did you get the login details?

**Comment by mhirdes** [comment]
I wrote you an answer.

**Comment by mhirdes** [comment]
The problem was an .htaccess protection. The server was not allowed to reach the frontend. 
The solution is to give the server access for the frontend, so that the curl call could work. So add the line in your .htaccess file and replace the x with the IP from the server.

`Allow from xxx.xxx.xxx.xxx`
