### ISSUE TITLE
[FEATURE] Do not add SiteTitle if total characters exceeds page.maxTitle

### ISSUE THREAD

**Issue by vmans** [clickstorm/cs_seo#102]
The title says it: if total characters in the title exceeds page.maxTitle, then do not add siteTitle and the separator (when cs_seo is configured to add siteTitle).

It's quite easy to add in function getFinalTitle I suppose.

**Comment by mhirdes** [comment]
Sry but in my opinion this would more confuse then it would help. Each editor can see in the SERP window, when the title gets to long and than choose manually to not add the sitetitle.

**Comment by vmans** [comment]
Thanks for your attention. Basically I agree. But I do not agree when it concerns websites with over 4,000 pages.

I implemented it for now in the source, it's a very simple modification. So please reconsider.

**Comment by mhirdes** [comment]
If you implemented this already, maybe you can add an option and a hint in the documentation for this. So that a TYPO3 admin can activate this feature if he would like to. If you than make a pull request here, I could integrate your changes.
