### ISSUE TITLE
Remove cHash from addQueryString.exclude

### ISSUE THREAD

**Issue by derhansen** [clickstorm/cs_seo#103]
I have some strange problems on a TYPO3 8.7 website using **cs_seo** together with **realurl**. For some reason, the **realurl** URL Data table did contain entries to pages, where the cHash parameter was missing. After some debugging, I found out, that the cHash is excluded in `lib.currentUrl` in the **cs_seo** extension, which is used to output the canonical URL.

AFAIK TYPO3 8.7 by default shows an 404 page for links to extension records (e.g. news), if no cHash is given. So if, for whatever reason, the TypoLink to the canonical URL is generated first, then URLs may show a 404 Error with the following error

![image](https://user-images.githubusercontent.com/2629896/27087811-481a237c-5056-11e7-9812-68317b0f3229.png)

I could not finally reproduce, when this problem occured, but shouldn't the TypoLink for `lib.currentUrl` always include a cHash?

**Comment by mhirdes** [comment]
Hey. I am not really sure about this. I think in the past there was a reason why we excluded the cHash. Nevertheless I removed the cHash there, because you are right, it is now a mandatory param. Thanks for your report.
