### ISSUE TITLE
Removing of canonical for records does not work.

### ISSUE THREAD

**Issue by poomer1988** [clickstorm/cs_seo#106]
Currently removing the canonical URL for records does not work. Only for normal pages it works correctly

**Comment by mhirdes** [comment]
Hey. What is the problem?

**Comment by poomer1988** [comment]
We want to remove the canonical URL for records and ad our own, but it does not work with:

```
# remove canonical
page.headerData.654.10 >
```
For normal pages it works correctly but if the page is a detail page this snippet does not work

**Comment by mhirdes** [comment]
Currently it is not possible to remove only the canonical tag for detail pages. The canonical tag for detail pages is set here https://github.com/clickstorm/cs_seo/blob/master/Classes/UserFunc/HeaderData.php and is generated with the lib.currentUrl https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/lib.currenUrl.ts  What is the problem with the canonical tag? If you don't want any meta tags from cs_seo on this page use `page.headerData.654 > `

**Comment by poomer1988** [comment]
Is it planned for the next releases, that we can also exclude only the metadata for detail pages in typoscript? 

It should be updated here so that it is possible to exclude the whole metadata for detailpages only by using 
`page.headerData.654 >`
https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/OverrideTypoScript/Index.html

Our problem is that we have the same news on serval pages and the detail page on the same page and to prevent duplicate content we have to remove the canonical and add our own

**Comment by mhirdes** [comment]
why you dont't modify the lib.currentURL?

**Comment by mhirdes** [comment]
you can already unset the whole metadata with `page.headerData.654 >`

**Comment by poomer1988** [comment]
We wrote a own Hook to render the canonical tag. But in the future it would be nice have a possibility to override specific meta tags for detail pages (pages with records and GET-Parameters).

**Comment by mhirdes** [comment]
you could add your hook as userfunc to the lib.currentUrl when the get param is set.
