### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by marcelbirrer** [clickstorm/cs_seo#107]
Error message in TYPO3 Backend while creating new page:

[1.1.12]: SQL error: 'Field 'tx_csseo_og_description' doesn't have a default value' (pages:NEW12345)

TYPO3 Version: 8.7.2
PHP 7.1.6
MySQL 5.7.18

**Comment by mhirdes** [comment]
hey, can't reproduce this error. Maybe we could take a look together via TeamViewer?

**Comment by mhirdes** [comment]
http://haraldwingerter.de/?p=705

**Comment by marcelbirrer** [comment]
thanks, i'll have a look with the provider then!

**Comment by mhirdes** [comment]
You're welcome

**Comment by mhirdes** [comment]
Hey. I solved the problem by removing the NOT NULL terms in the ext_tables.sql. Please update your DB via Database Analyzer.

**Comment by marcelbirrer** [comment]
hello! changed the SQL Mode to the original state and it works with 2.1.1-dev, thanks!
