### ISSUE TITLE
No max length, if total characters exceeds page.maxTitle

### ISSUE THREAD

**Issue by mindbreaker** [clickstorm/cs_seo#109]
The maxTitle and maxDescription are good indicators for the correct length of the title and description.
But in my opinion, it should not prevent the user from entering more characters.

**Comment by mhirdes** [comment]
Hi. So what is your suggestion? You can increase the numbers of available signs in the extension configurations. Or you override
```
$GLOBALS['TCA']['pages']['columns']['title']['config']['max'] = $extConf['maxTitle'];
$GLOBALS['TCA']['pages']['columns']['nav_title']['config']['max'] = $extConf['maxNavTitle'];
$GLOBALS['TCA']['pages']['columns']['description']['config']['max'] = $extConf['maxDescription'];
```
by yourself?

**Comment by mindbreaker** [comment]
Hi Marc,

i would only use it as a hint, but not as a restriction.
If a text is a few characters longer,  you should also be able to enter more characters.

**Comment by mhirdes** [comment]
The Backend in TYPO3 dose not provide this feature by default. Therefore we would have to write own input fields. Furthermore there had to be a config, where the integrator can select, if the length is only a hint. I prefer the current implementation. But if you would like to have this feature, you can create a pull request.
