### ISSUE TITLE
Error when checking for broken extensions

### ISSUE THREAD

**Issue by frank79a** [clickstorm/cs_seo#11]
Hi, I'm getting the following error when I'm checking for broken extensions after installing cs_seo 1.4.1 :

Call to a member function exec_SELECTquery() on a non-object in /var/www/typopro/typo3_src-6.2.25/typo3/sysext/backend/Classes/Utility/BackendUtility.php on line 370

**Comment by mhirdes** [comment]
Hi,

thanks for you your advice. It's already fixed. #6 New version will be released next week.

**Comment by frank79a** [comment]
Oups! Sorry I missed that. Thanks!
