### ISSUE TITLE
please add functionality for ext:just_news / make allowedDoktypes working

### ISSUE THREAD

**Issue by manuelbachl** [clickstorm/cs_seo#111]
Hi there,
atm we're trying to integrate cs_seo with just_news. But unfortunately this isn't possible yet. The Field allowedDoktypes seems not working.
Would be great to have this fixed, because the client wants to go live next few weeks ;-)

Best
Manuel

**Comment by mhirdes** [comment]
Hey. Maybe you can test the current dev version, a bugfix is there included. Kind regards, Marc
