### ISSUE TITLE
hreflang does not work: Method getCurrentTable returns always false.

### ISSUE THREAD

**Issue by mkarulin** [clickstorm/cs_seo#112]
> \Clickstorm\CsSeo\UserFunc\HeaderData\getCurrentTable()

Currently hreflang tags do not work. `if (isset($tables[$key . '.']['enable'])) {...}` returns  "false", because it checks if `['hreflang.' . '.']['enable']` is set.
As 'hreflang.' already contains a period, no additional period should be appended.

**Comment by mhirdes** [comment]
Hi. Which version of TYPO3 and cs_seo do u use?

**Comment by mkarulin** [comment]
Typo3 8.7.3
cs_storm 2.1.1-dev

**Comment by mhirdes** [comment]
Tested it again and it works like it should. 
Configs are e.g.
```
plugin.tx_csseo.hreflang.enable = 1
plugin.tx_csseo.hreflang.ids = 0,1
plugin.tx_csseo.hreflang.keys = de,en
```
Take also a look here:
https://docs.typo3.org/typo3cms/extensions/cs_seo/Configuration/Language/Index.html 
Otherwise you can send me a temporary access to your backend or we take a look via TeamViewer.
