### ISSUE TITLE
no company name after pipe

### ISSUE THREAD

**Issue by Toccamonium** [clickstorm/cs_seo#113]
Hi,
What do I have to change to get the company name after the pipe sign? Right now I just get the page title, after | is empty.

thanks, Florian

**Comment by mhirdes** [comment]
Hi,

there are two ways. You can set the title like it used in the core by adding it as the website title in your TypoScript Root Template or you add the title via TypoScript, so you provide it in different languages. More info you will get in the extension manual https://docs.typo3.org/typo3cms/extensions/cs_seo/Configuration/Language/Index.html#sitetitle

I hope that this answer is helpful to you.

Kind regards,
Marc
