### ISSUE TITLE
anonymizeIp is needed

### ISSUE THREAD

**Issue by webdev2027** [clickstorm/cs_seo#114]
Hi,
It's nice to insert your own Google Analytics UA-XXXXXXX-XXX in the template constants.

But the output should also include :` ga('set', 'anonymizeIp', true);`
Maybe also as a constants checkbox, (default = checked)

Thanks
Stefan

**Comment by mhirdes** [comment]
Hi Stefan, 

Thanks for your Feedback. This line is already included, as you can see here https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/tracking.ts If you need an other Tracking Code you can change the .wrap

I hope this information helps you.

Kind Regards,
Marc

**Comment by webdev2027** [comment]
Hi Marc.
I've insert my UA-Code at  constants and get the output:
![ga](https://user-images.githubusercontent.com/5501876/28421864-b1b9b4e6-6d66-11e7-920e-3ad72ce9d0af.png)


Maybe I've made a mistake or did I forget something?

**Comment by mhirdes** [comment]
Hey, 
this code is not generated from cs_seo. cs_seo places the tracking code in the header. Make sure that u use the current version of cs_seo. 
Kind regards,
Marc

**Comment by webdev2027** [comment]
Hi marc.
cs_seo 2.1.1, TYPO3 7.6.20,  php5.6
`plugin.tx_csseo.tracking.googleAnalytics = UA-1026...`
I will check this, I took over the project from another developer, so maybe there's sth. another header/footerData .. in TS. Thanks anyway. 

Regards 
Stefan
