### ISSUE TITLE
Something Changed betwen TYPO3 7.X and 8.7.4 regarding croping Images (Facebook & twitter)?

### ISSUE THREAD

**Issue by funkyferdy** [clickstorm/cs_seo#116]
Yesterday i Updated my typo3 and "suddenly" i can not crop the facebook and twitter image anymore

**Comment by mhirdes** [comment]
Hey, 

yes thanks for the hint. It's fixed in the master branch. If you like to, you can test it. 

Kind Regards,
Marc

**Comment by funkyferdy** [comment]
Works like a charm again :)
