### ISSUE TITLE
Add a possibility to change speaking URL path segment transliteration rules

### ISSUE THREAD

**Issue by vuxorpadd** [clickstorm/cs_seo#117]
When changing the page title, cs_seo automatically updates speaking URL path segment. When doing so it uses some hard coded transliteration rules. For ex.: 'ä' => 'ae'. It would be good to have a possibility to change those rules. So for ex. 'ä' => 'a'.

**Comment by mhirdes** [comment]
Hi. Thanks for your feedback. I think about where to store this settings. If you like to, you could also add a pull request.

**Comment by mhirdes** [comment]
Hi. Any news for this issue? Do you prefer a storage for this config?

**Comment by mhirdes** [comment]
What do you think about to store the URL of the jquery.seourl.js in TypoScript. So you can change the URL and modify the JS like you want to?
