### ISSUE TITLE
Documentation outdated "Override TypoScript"

### ISSUE THREAD

**Issue by nebrot** [clickstorm/cs_seo#118]
Since commit [[BUGFIX] avoid TypoScript conditions](https://github.com/clickstorm/cs_seo/commit/2b751f1c559f4b6ac51c6bfd0df78ea1a52e9f99) (v2.1.2) the chapter ["Override TypoScript"](https://github.com/clickstorm/cs_seo/blob/master/Documentation/Developer/OverrideTypoScript/Index.rst) in docs is outdated, for example

```
# remove meta description
page.meta.description >

# remove robots
page.meta.robots >
```

should be i think:
```
# remove meta description
page.headerData.654.7 >

# remove robots
page.headerData.654.15 >
```

**Comment by mhirdes** [comment]
Thanks for you support. It's fixed.
