### ISSUE TITLE
Parse errors after including the cs_seo static template

### ISSUE THREAD

**Issue by frank79a** [clickstorm/cs_seo#12]
Typo3 version : 6.2.25

Hi, after including the cs_seo static template, I still get this error when I try to access the page settings :
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/typopro/fadq/typo3conf/ext/cs_seo/Classes/UserFunc/PreviewWizard.php on line 81

Also, if I try to access other modules like the Extension Manager, the Log or the Install Tool, I get the following error :
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/typopro/fadq/typo3conf/ext/cs_seo/Classes/UserFunc/HeaderData.php on line 47

**Comment by clickstorm** [comment]
Hi,

could it be, that you use a PHP version < 5.5?

**Comment by frank79a** [comment]
Yes. PHP 5.4.45.

**Comment by mhirdes** [comment]
:( could you update the Version to 5.5? Otherwise I must make cs_seo compatible for this old PHP Version.

**Comment by frank79a** [comment]
I will. But could you add the PHP version to the dependencies in the extension page from the repository :
https://typo3.org/extensions/repository/view/cs_seo

Thank you for your help!

**Comment by clickstorm** [comment]
I think to make it compatible is not the big deal. Wait a moment.

**Comment by clickstorm** [comment]
Maybe it's a bigger deal and also a step back. So I will add it as dependency.
