### ISSUE TITLE
Avoid double htmlentity encoding

### ISSUE THREAD

**Issue by apxlrt** [clickstorm/cs_seo#120]
When the Typo3 editor is configured to encode html entities those entities get double encoded in your escapeContent function
I think setting the double_encode parameter to false in your htmlentities function would fix the problem

**Comment by mhirdes** [comment]
Hey. Which versions of TYPO3 and cs_seo do u use? And sry, but I didn't get the part or the code where the error occurs.

**Comment by apxlrt** [comment]
Typo3 Version: 8.7.4
cs_seo: 2.1.2

The error only appears when you use a fallback field with RTE for the description and the entities are already encoded in the database. 

You can find the code in your escapeContent function in the  HeadeData.php file (line 438)

**Comment by mhirdes** [comment]
Hey. 

Fixed the issue. Maybe you like to test and give feedback.

Kind regards,
Marc
