### ISSUE TITLE
Add possibility to control the display of the evaluation results in the page module on user/group level

### ISSUE THREAD

**Issue by twllndr** [clickstorm/cs_seo#122]
Currently it's possible to show the evaluation result in the page module in the header, the footer or hide it completely. It would be nice, to be able to control, which user or group is able to see the evaluation results. The position (header, footer) can always be the same and rely on the setting in the extension manager. But maybe this information is just relevant for some special user(s) or usergroup(s).

**Comment by mhirdes** [comment]
Hey. Sry for that late answer. But this is already possible with userTSconfig.

```
mod.web_layout.tx_csseo.disable = 1
```
This is also mentioned in the extension manual https://docs.typo3.org/typo3cms/extensions/cs_seo/Administrator/ExtensionManagerConf/Index.html#evaluation-inpagemodule

I hope this resolves your issue.

Kinde Regards,
Marc
