### ISSUE TITLE
Saving pages sometimes produces "Localization failed;" error and creates multiple copies of relations

### ISSUE THREAD

**Issue by dacostafilipe** [clickstorm/cs_seo#134]
On some pages, when saving, I get the following error:

```[newlog()] Localization failed; Source record contained a reference to an original record that is not a default record (which is strange)!```

Just before this error crashed the execution, Typo3 creates multiple copies of relations bound to "tx_csseo_og_image" or/and "tx_csseo_tw_image" of some other page.

This leaves me with pages that have a long list of images:

![screen shot 2017-09-28 at 12 05 12](https://user-images.githubusercontent.com/922998/30973285-0c9a746c-a46d-11e7-99c3-f09aa2329e8a.png)

I was not able to find a direct relation between those pages or why specific relations where copied and others not. I'm also not able to create a new page that triggers this error, but if using a DB dump with "broken" pages this happens 100% of the time.

Disabling the cs_seo extension does solve the issue.

Disabling 'l10n_mode = exclude' in the cs_seo TCA configuration also solves the issue, but we are still testing if this has other repercussions (https://github.com/dacostafilipe/cs_seo/tree/l18n-mode-exclude-issue)

**Comment by mhirdes** [comment]
Thanks a lot for your report. Tested with TYPO3 7.6 and 8.7 and it works without the l10nmode.
