### ISSUE TITLE
Add possibility to edit SEO data of custom page types

### ISSUE THREAD

**Issue by mkarulin** [clickstorm/cs_seo#135]
Currently the fields of custom page types are grayed out in SEO module even if the custom page doktypes have been added to the doktypes evaluation field in the Extension Manager.
The enabled doktypes seem to be hard-coded in CsSeoController.js 

```
csSEO.gridOptions.columnDefs[key].cellClass = function(grid, row, col, rowRenderIndex, colRenderIndex) {
    if(!(row.entity.doktype == "1" || row.entity.doktype == "6")) {
        return 'text-muted';
    }
}
```

**Comment by mhirdes** [comment]
64e82eddac2bece96624323d27b3bec2e2cd1bad it's solved.

**Comment by mkarulin** [comment]
Hi.
Unfortunatelly now all doctypes are grayed out in the SEO Module. I can confirm this is the issue with current master.

**Comment by mhirdes** [comment]
yeah, the doktype is in 8.7 an integer. In 7.6 a string. Now it works in 8.7, too
