### ISSUE TITLE
Google URL preview issue on multidomain installations

### ISSUE THREAD

**Issue by codekapitaen** [clickstorm/cs_seo#137]
When you're logged in with domain-a.de, the Google URL preview only works in the page tree, which uses domain-a.de as domain record. If you want to get previews for other domains, you have to log in by using the specific domain.

**Comment by mhirdes** [comment]
hey. fixed in master. maybe you like to test.

**Comment by codekapitaen** [comment]
Hey, thanks a lot ... works fine! :)
