### ISSUE TITLE
twitter:site and twitter:creator

### ISSUE THREAD

**Issue by SimonWpt** [clickstorm/cs_seo#140]
cs_seo shows `twitter:site` or if empty `twitter:creator`

https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/Meta/twitterCards.ts#L32

> Excerpt from https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup

**twitter:site**
@username of website. Either twitter:site or twitter:site:id is required.
*Used with summary, summary_large_image, app, player cards*

**twitter:creator**
@username of content creator
*Used with summary_large_image cards*

cs_seo should respect the different purpose of both usernames. If a publisher has different products accounts, it would be something like:

```
<meta name="twitter:creator" content="@puplisher_username" />
<meta name="twitter:site" content="@produkt_username" />
```

**Comment by mhirdes** [comment]
Is there a case when you need different twitter:site for one domain?

**Comment by SimonWpt** [comment]
No. I think, one twitter:creator and one twitter:site per domain is sufficient, i.e.:

```
<meta name="twitter:creator" content="@VW " />
<meta name="twitter:site" content="@vwgolfv" />
```

**Comment by mhirdes** [comment]
It's online :) Maybe you like to test.
