### ISSUE TITLE
The news can not be saved

### ISSUE THREAD

**Issue by blueroger** [clickstorm/cs_seo#141]
Hello,
I can not save the news. I use typo3 8.7.6, themes, t3kit, tx_news

When saving the news, I get the following error message:

Oops, an error occurred!
An exception occurred while executing 'SELECT `uid`, `l10n_parent`, `fe_group`, `bodytext`, `categories`, `related`, `related_from`, `related_links`, `internalurl`, `externalurl`, `content_elements`, `tags`, `fal_media`, `fal_related_files`, `tx_csseo`, `deleted`, `t3ver_wsid` FROM `tx_news_domain_model_news` WHERE `uid` = ?' with params [1]: Unknown column 'tx_csseo' in 'field list'

Thank you.

**Comment by mhirdes** [comment]
Hey. 

If you set the pageTSconfig to extend the news, then please insert the tx_csseo column to the news table as it is explained here https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/ExtendExistingModel/Index.html 

Kind regards,
Marc
