### ISSUE TITLE
<meta name="copyright" content="xxx">

### ISSUE THREAD

**Issue by SimonWpt** [clickstorm/cs_seo#142]
The copyright meta-tag will used to make visible, that the content (text, images, videos etc.) is protected. It can be important, if content is copied without permission. It wil be used for trademarks, patents or intellectual property.

The dublin core has similar tags:

http://dublincore.org/documents/dcmi-terms/#terms-rights
http://dublincore.org/documents/dcmi-terms/#terms-rightsHolder
http://dublincore.org/documents/dcmi-terms/#terms-dateCopyrighted

I am not sure, if this is a important legal issue.

**Comment by mhirdes** [comment]
Thanks for your hint. IMO this is not a case for editors. So it can be added via TypoScript, where cs_seo is not required.
