### ISSUE TITLE
[BUG] Can't edit pages of type "folder"

### ISSUE THREAD

**Issue by jwittorf** [clickstorm/cs_seo#143]
Using latest 2.2.1-dev e3ea8ce342c0be6773c0acb7e5f8c599ee1ecf95 and TYPO3 7.6.23

I can't edit pages of type "folder", this shows up in the chrome console:

```
Uncaught TypeError: Cannot read property 'seoURL' of undefined
    at updatePathSegment (/web/typo3conf/ext/cs_seo/Resources/Public/JavaScript/jquery.cs_seo.path.js?1512317582:44)
    at HTMLDocument.<anonymous> (/web/typo3conf/ext/cs_seo/Resources/Public/JavaScript/jquery.cs_seo.path.js?1512317582:34)
    at fire (jquery-2.1.4.js:3099)
    at Object.fireWith [as resolveWith] (jquery-2.1.4.js:3211)
    at Function.ready (jquery-2.1.4.js:3417)
    at HTMLDocument.completed (jquery-2.1.4.js:3433)
```

I guess it's because the page doesn't have the specific field and there is some JS-action trying to work with the non-existing field.

**Comment by mhirdes** [comment]
Usually the doktype for folders is not affected by cs_seo. Did you changed the evaluation settings in the extension manager?

**Comment by jwittorf** [comment]
Thanks for looking into the issue, it's been a while so I'm not 100% sure, this is what I've got:

![image](https://user-images.githubusercontent.com/2085721/35119565-aa2f0f1e-fc95-11e7-89fa-1676f2581201.png)

![image](https://user-images.githubusercontent.com/2085721/35119579-b214a3a6-fc95-11e7-9514-d3d8e8da524b.png)

![image](https://user-images.githubusercontent.com/2085721/35119590-bc8dc1f0-fc95-11e7-87c4-25b73bacc854.png)

I'm not sure but I might have changed the max. characters for the title (page.maxTitle).

**Comment by mhirdes** [comment]
Looks fine. Maybe we can take a look together in your installation?

**Comment by mhirdes** [comment]
hirdes@clickstorm.de

**Comment by medarob** [comment]
I have the same error with Typo3 7.6.24 and the newest cs_seo extension.

Removing the extension from the template doesn't solve the issue. I have to deactivate the extension in the extensionlist to solve it but then I can't use the extension anymore.

**Comment by mhirdes** [comment]
Hey. I can only offer you, to take a look together thorugh your installation. Please contact me by hirdes@clickstorm.de

**Comment by mhirdes** [comment]
Bugfix is online. Next week there will be a bugfix release.
