### ISSUE TITLE
Exclude pages from opengraph feature via id list possible?

### ISSUE THREAD

**Issue by hilburger** [clickstorm/cs_seo#144]
Hi there! 
Great extension, just one problem: 
We have a custom news extension which includes it's own socialgraph tags. 
Now the settings for normal pages are always added before our custom tags within news articles. 

Like this we are getting two blocks with these meta tags which is not really nice. 
Is there a way to set up an exclude list via TS so that these pages are excluded from adding cs_seo-opngraph-tags? 

Thank you!

**Comment by mhirdes** [comment]
Hi, everything is configurable via TypoScript https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/OverrideTypoScript/Index.html
