### ISSUE TITLE
User-rights in SEO module not working properly

### ISSUE THREAD

**Issue by tobikummer** [clickstorm/cs_seo#148]
Using TYPO3 8.7.9 and cs_seo 2.2.0

If all the fields for the SEO-module are "readable & writable" for an BE editor, he can see all the fields in the SEO-module. So far, so good. 
Navigate to the SEO-module, choose "Index".
If an editor tries to set the tick for example in the column "no index", he can do so. The "green success feedback" comes up, no AJAX error is dispatched. 
If the editor reloads his browser, the tick is away, in the database is a 0 instead a 1. 
If I'm logged in as TYPO3 admin, all works fine

**Comment by mhirdes** [comment]
Hey, sry but I can't reproduce this error. In my installation it works as expected. Maybe we should take a look together on yours?
