### ISSUE TITLE
[BUG] Since 1.5.1 PageConfiguration wont open

### ISSUE THREAD

**Issue by grimmcreative** [clickstorm/cs_seo#15]
Since 1.5.1 blank site when opening Page Configuration

**Comment by mhirdes** [comment]
There were only two small changes. Did you clear all caches? Database analyzer update? Which TYPO3 Version do you use? Do you use the dev Version?

**Comment by mhirdes** [comment]
Maybe you can activate the Debug Settings and give me an error message?

**Comment by grimmcreative** [comment]
TYPO3 7.6.10 
cs_seo 1.5.1 TER Version
As i see it only accurs no root page
Activated Debugging - no errors are shown

**Comment by mhirdes** [comment]
Which Version do you use before? Do you run the Database Analyzer?

**Comment by grimmcreative** [comment]
Its on a fresh installation - no Version before.
Database Analyzer says nothing.
On other Projects everything is working good after update to 1.5.1 - there i had 1.4.xdev before

**Comment by mhirdes** [comment]
Did you include the TypoScript?

**Comment by grimmcreative** [comment]
Sure

**Comment by mhirdes** [comment]
Do you have acces tot the PHP error log?

**Comment by grimmcreative** [comment]
Sure

**Comment by grimmcreative** [comment]
No Errors there

**Comment by mhirdes** [comment]
Sry, but I don't know what to do. I completely reinstalled the extension (delete DB entries an typo3temp). No error occures. Which PHP Version u use?

**Comment by grimmcreative** [comment]
PHP 5.6.24
i am currently deleting the hole project and make new install.

**Comment by mhirdes** [comment]
ok

**Comment by grimmcreative** [comment]
Lol. Complete fresh installation. 
Just some basic setup - install cs_seo - pageConfiguration - Blank Site on Root Page

**Comment by grimmcreative** [comment]
Issue only occurs on Page with ID 1

**Comment by mhirdes** [comment]
You said before it only occurs if the page is no root page?

**Comment by grimmcreative** [comment]
Rofl - damn - shame on me
I found it.
i was logged in with http instead of https - with https it works.

oh sorry for missspelling before.

**Comment by grimmcreative** [comment]
No Issue there. Just check which protocol is used.

**Comment by grimmcreative** [comment]
Thanks for your Help and sorry for disturbing because of this
