### ISSUE TITLE
Meta description translation overwritten by default lang

### ISSUE THREAD

**Issue by MichiBeck** [clickstorm/cs_seo#152]
Hi, 
I´m working with TYPO3 8.7.9 and cs_seo 2.2.1-dev.

After translate the meta description fields, they appear only in the og:description meta tag. The regular meta desciption tag uses the value from the default language. I looked at the ts-settings and there is nothing, wich should overwrite the cs_seo settings.

Can someone reproduce this?

Thank you in advance.
Michael

**Comment by mhirdes** [comment]
Hi, tested it again and it works as it should. Really check your TS in the TS browser. Otherwise I can take a look if you give me access. Kind Regards, Marc

**Comment by MichiBeck** [comment]
Thanks for your reply - I checked again and the only configuration is the one, cs_seo has...

**Comment by mhirdes** [comment]
So should I take a look?

**Comment by MichiBeck** [comment]
Yes please.

**Comment by mhirdes** [comment]
hirdes@clickstorm.de

**Comment by mhirdes** [comment]
Hi.

I have inserted in your TS 

```
page.headerData.654.7.field >
page.headerData.654.7.data = page:description
``` 

now it works. But its a strange behaviour. Because

```
page.headerData.654.7.field = description
``` 

should also work.

Maybe some config overwrites this field... I will modify this TS lines in cs_seo. So you can use it.

**Comment by MichiBeck** [comment]
Perfect, thank you very much! Great work!!!
