### ISSUE TITLE
Wrong hreflang declaration on records and not default language

### ISSUE THREAD

**Issue by apxlrt** [clickstorm/cs_seo#155]
Custom records displayed in languages other than the default language are showing only hreflang meta tag from the current language.

The getAllLanguagesFromItem function must include the original record uid for the pointerfield in the where clause

**Comment by mhirdes** [comment]
Hi, this is already the case. For example here is my generated code for an english news record.

```html
<link rel="canonical" href="http://typodummy-8-7.local.clickstorm.de:8070/en/translate-to-english-news/english-news" />
<link rel="alternate" hreflang="de" href="http://typodummy-8-7.local.clickstorm.de:8070/news/german-news" />
<link rel="alternate" hreflang="en" href="http://typodummy-8-7.local.clickstorm.de:8070/en/translate-to-english-news/english-news" />
```

Or did I understand your issue wrong?

**Comment by apxlrt** [comment]
Seems strange - in my case I only get the translated record because the `uid` parameter from the `getAllLanguagesFromItem` function has the uid from the translated record and not from the default record. So the where clause `'(' . $pointerField . ' = ' . $uid . ' OR uid = ' . $uid . ')'` only returns the current displayed record

**Comment by mhirdes** [comment]
Is `$GLOBALS['TCA'][$table]['ctrl']['transOrigPointerField']` set for your records?

**Comment by apxlrt** [comment]
`transOrigPointerField` field is set for the records - I will have a closer look at the issue and debug the whole process in my project and come back with my findings

**Comment by mhirdes** [comment]
Hi, are there any news on this topic?

**Comment by apxlrt** [comment]
Sorry, seems like a linking issue on our side - the wrong ID gets passed

**Comment by mhirdes** [comment]
Ok, than I close this issue.
