### ISSUE TITLE
canonical for multi-languages not working

### ISSUE THREAD

**Issue by nabossha** [clickstorm/cs_seo#157]
it seems that storing canonical URL's in the backend does not work when using multiple languages:

you cannot edit the canonical URL of other languages within the page / translated page because the tx_csseo_canonical seems missing in /Configuration/TCA/Overrides/pages_language_overlay.php  (though it is correctly defined in ext_tables.sql within pages_language_overlay)

also, storing canonical URL's for multiple languages within the provided backend-module does not work because of this bug.

can you please fix this in your TCA?

**Comment by mhirdes** [comment]
Do you really need this. Usually the canonical is for the default language. All other things are done by href lang

**Comment by fjacobi** [comment]
I think it is necessary, especially if Google is going forward with their URL cleanups, which might be based on the canonical.

https://www.androidpolice.com/2018/02/19/chrome-now-automatically-cleans-messy-urls-share/

**Comment by nabossha** [comment]
i think it is necessary to have proper setup , see for example here: [https://yoast.com/rel-canonical/#canonical-hreflang](https://yoast.com/rel-canonical/#canonical-hreflang)
also, currently the canonical-tag in another language in the frontend is empty(!) which makes this even worse

**Comment by mhirdes** [comment]
@nabossha is implemented. Maybe you like to test?

**Comment by nabossha** [comment]
@mhirdes just tested it and can confirm it works as expected using 2 languages. i hope to see a new  release of your fantastic extension soon since we use an automated deployment it's not a good way to patch it manually :)

**Comment by mhirdes** [comment]
It's planned for this friday.
