### ISSUE TITLE
Optimierung des Piwik JS Codes

### ISSUE THREAD

**Issue by CarstenHager** [clickstorm/cs_seo#158]
Hallo, 

sorry ich spreche leider kein Englisch, daher schreibe ich es in Deutsch.

Wenn ich euren Code bei Google PageSpeed durchlaufen lasse, erhalte ich folgende Meldung.
https://www.dropbox.com/s/3siku2grj2kucor/Screenshot%202018-03-04%2016.34.49.png?dl=0

Um dies zu beheben müsste man 2 Zeilen im Code ändern.

```
**alt**
_paq.push(['setTrackerUrl', u+'piwik.php']);
**neu**
_paq.push(['setTrackerUrl', u+'js/']);

**alt**
g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'/js/piwik.min.js'; s.parentNode.insertBefore(g,s);
**neu**
g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'js/'; s.parentNode.insertBefore(g,s);
```

Dann hat auch GooglePageSpeed nichts mehr zu "mosern".

Gruß Carsten

**Comment by mhirdes** [comment]
Danke für deine Hilfe und sry für die späte Antwort. Die Integration des Tracking-Codes lässt sich auch mit `page.jsInline.654.20.wrap` indivuell anpassen. In der cs_seo 3.0 wird die Änderung dann enthalten sein.
