### ISSUE TITLE
googleAnalitics - wrong wrap logic on 2.3.0

### ISSUE THREAD

**Issue by rupasix** [clickstorm/cs_seo#159]
You've changed js script for google analitics and now you have 2 places for api key:
[here](https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/Tracking/googleAnalytics.ts#L7) and [here](https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/Tracking/googleAnalytics.ts#L10) but still wrap with splitchar is used ([here](https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/Tracking/googleAnalytics.ts#L30)).

When constant is set, string is rendered in <head> but is cutted on second hash and it's breaking whole page because <script> tag is never closed.

![image](https://user-images.githubusercontent.com/9860558/37026085-a6aeecb2-212d-11e8-8d2b-51feeea236cc.png)

**Comment by grimmcreative** [comment]
In my case this issue causes a blank page.

**Comment by WebDevJona** [comment]
Hey,

I've prepared a PR (#160) for this that uses two wraps for each script tag.

Kind Regards,
Jonathan

**Comment by mhirdes** [comment]
Thanks a lot. New bugfix release is online.
