### ISSUE TITLE
Consider $GLOBALS['TSFE']->altPageTitle

### ISSUE THREAD

**Issue by SventB** [clickstorm/cs_seo#162]
When building the title tag, you should consider $GLOBALS['TSFE']->altPageTitle. TYPO3 also builds the title tag with this variable (PageGenerator.php, line 1053):
```php
$tsfe->altPageTitle ?: $tsfe->page['title']
```
So you should write (PageTitle.php, line 62):
```php
$title = empty($GLOBALS['TSFE']->altPageTitle) ? (empty($page['tx_csseo_title']) ? $page['title'] : $page['tx_csseo_title']) : $GLOBALS['TSFE']->altPageTitle;
```
One of the advantages of this is, that EXT:cs_seo is able to generate the title tag for EXT:news.

**Comment by mhirdes** [comment]
What is there in your altPageTitle? The thing is, we then have also to respect this in the backend... etc.

**Comment by SventB** [comment]
EXT:news and other extensions use the "altPageTitle" to set the browser title.

**Comment by SventB** [comment]
I've added the predefined Page TSConfig for EXT:news, but then field "alternative_title" (EXT:news uses this field to manipulate the browser title) isn't considered for the browser title.

You really should use "altPageTitle", because the TYPO3 core provides and also uses this variable to build the browser title.

**Comment by mhirdes** [comment]
We could provide multiple fallback fields in the pageTSconfig. Then you could also add the alternative_title field. The thing is, we want to provide an easy way to extend any database record with SEO options, not just news. I also can take a look to the altPageTitle. But then you can't use the cs_seo SEO fields for this records.

**Comment by SventB** [comment]
Both suggestions are good, I would prefer you implement both ;)
The big advantage of TYPO3 is its flexibility and the TYPO3 extensions should be flexible useable, too.

Some extensions might set "altPageTitle" in the controller action functions, so you really should consider of supporting variable "altPageTitle".

**Comment by mhirdes** [comment]
The problem is, that I can't show this altPageTitle in the Google SERP in the backend. Also the modification to hide the suffix/prefix is not working than. If I have time left, I will think about this. First I will implement the multible fallbacks. Feel free to add a pull request if you need the altPageTitle in the next days.

**Comment by clickstorm** [comment]
Thanks to @Nemo64 . I will not support this feature or test it. For news and other records you can extend the record with the SEO fields incl. fallbacks for title, description etc. Then the browser title will match the news title automatically. https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/ExtendExistingModel/Index.html

**Comment by SventB** [comment]
@clickstorm I'm a little bit confused: In the current version of EXT:cs_seo, the title is built with $GLOBALS['TSFE']->altPageTitle (which is fine for me). But didn't you say you won't implement this?
