### ISSUE TITLE
TYPO3 9: ExtensionManagementUtility::registerAjaxHandler removed

### ISSUE THREAD

**Issue by christian-fries** [clickstorm/cs_seo#163]
The usage of ExtensionManagementUtility::registerAjaxHandler was deprecated in TYPO3 8 and was removed in TYPO3 9. 
Further information: https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.0/Deprecation-73352-DeprecateOld-schoolAJAXRequests.html

**Comment by mhirdes** [comment]
Hi, thanks. The current version is for 7.6 and 8.7. If I have time in the next days/weeks there will be a realease for 8.7/9.x.

**Comment by christian-fries** [comment]
No hurry, I just experienced this issue when trying to update a demo project to TYPO3 9. I thought I file a report.
