### ISSUE TITLE
don't use addQueryString for a canonical url

### ISSUE THREAD

**Issue by Nemo64** [clickstorm/cs_seo#171]
I noticed that this extension uses `addQueryString` to generate a link to the current page.
While it is easier than the manual way, I think I have a better solution.

I figured that it is possible to tab into the cHash mechanism to get all parameters that typo3 considers for the cache which is basically perfekt. Any parameter that does not change the page (or at least not the cache) is excluded.

Here a small glimpse at how that would work

```PHP
namespace Extension\Hook;

class CanonicalParametersGetDataHook implements ContentObjectGetDataHookInterface
{
    public function getDataExtension($getDataString, array $fields, $sectionValue, $returnValue, ContentObjectRenderer &$parentObject)
    {
        if ($getDataString !== 'canonical_parameters') {
            return $returnValue;
        }

        $cHash_array = $GLOBALS['TSFE']->cHash_array;
        unset($cHash_array['encryptionKey']);
        return GeneralUtility::implodeArrayForUrl('', $cHash_array);
    }
}

// ext_localconf.php
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_content.php']['getData'][$_EXTKEY] =
    \Extension\Hook\CanonicalParametersGetDataHook::class;
```

```
# canonical url
10 = TEXT
10 {
    wrap = <link rel="canonical" href="|">
    typolink.parameter.data = page:uid
    typolink.additionalParams.data = canonical_parameters
    typolink.forceAbsoluteUrl = 1
    typolink.returnLast = url
    # language is handled by linkVars
}
```

I'm not yet sure if i'll use cs_seo in the future yet. If I do, than i'll probably implement that myself. But I thought I add this advise now anyways.

**Comment by clickstorm** [comment]
Great. Is included. Thanks a lot for this hint.
