### ISSUE TITLE
TCA Migrations for TYPO3 8.7

### ISSUE THREAD

**Issue by comsolitag** [clickstorm/cs_seo#173]
In your Extension there are some TCA Migrations for TYPO3 8.7 pending.

In the TYPO3 Installtool you can see it.

**Comment by clickstorm** [comment]
Thanks for the hint, we know this and it is ok. The current release is for 7.6 and 8.7. 

TCA migrations will be done in the major realease cs_seo 3.0. They are aleady prepared in the dev-master.
