### ISSUE TITLE
Piwik Tag seems broken

### ISSUE THREAD

**Issue by SicorDev** [clickstorm/cs_seo#174]
Hello,

we configured in constants:

plugin.tx_csseo.tracking.piwik = www.customer.de/statistik

Which generates this tracking code:

var u="//www.customer.de/statistik/";
...
g.src=u+'/js/piwik.min.js';

Result is: https://www.customer.de/statistik//js/piwik.min.js

=> Which can't be loaded because of the double slash.

**Comment by clickstorm** [comment]
Usually this should not affect the loading. But it's fixed in the master. Maybe you can test and give feedback.

**Comment by SicorDev** [comment]
Okay, fine, then I'll just wait for the next version. Thank you very much!
