### ISSUE TITLE
Google Preview (SERP) generates wrong realURLs in multidomain context

### ISSUE THREAD

**Issue by kraemer-igroup** [clickstorm/cs_seo#176]
Hi,

on a multidomain installation a problem occured, that almost all pages had an additional entry with "/" as speaking url. Those entries are genereated by just editing the page properties and it looks like the cs_seo SERP is responsible for it.
I could reproduce this on our 8.7.11 installation with the following steps (cs_seo 2.3.3, realurl 2.3.2):
* Log in into the TYPO3 backend. The rootpage_id of the login domain is 123
* Open page properties of a page which is not inside the domain we are logged in with
* The page becomes a realURL entry with speaking URL "/" and rootpage_id "123"
* The URL within SERP is only correct on pages within the login domain

I could "fix" this by adding the following TypoScript Setup: _pageCsSeo.config.tx_realurl_enable = 0_
But of course there are no nice urls within SERP anymore...

Is there already a way to handle the urls within the SERP in multidomain installations? I tried adding  _pageCsSeo.config.baseURL_ without any chages.

**Comment by clickstorm** [comment]
Hi,

sry but I can't repoduce this. We haven't got this kind of problems. Please provide me an access to your stytem or we'll take a look together via TeamViewer.

Kind regards,
Marc
