### ISSUE TITLE
news url not get

### ISSUE THREAD

**Issue by anujaunds** [clickstorm/cs_seo#179]
i used cs_seo plugin for  create sitemap. its properly create the pages  sitemap but i  faced problem with news url. it show only date with news sitemap. please let me what i can do to resolve this problem

**Comment by mhirdes** [comment]
Hi. If the URL of each news in the sitmap is wrong you should check your RealURL config. Otherwise can you provide me an example? Kind regards, Marc

**Comment by anujaunds** [comment]
But it's url is working with frontend. that is Xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc/>
<lastmod>2018-06-22</lastmod>
</url>
<url>
<loc/>
<lastmod>2018-06-28</lastmod>
</url>
</urlset>

**Comment by mhirdes** [comment]
Ok. The loc has no attribute. Didn't see this before. We use typolink to create the urls. Also the sitemap has another page type. Realurl should there also work. Can you check if you set config.tx_realurl_enable or page.config.tx_realurl_enable? The second would not work. I can also offer you to take a look through your config tomorrow.

**Comment by anujaunds** [comment]
which config file you need. should you please let me.
pages url is working properly
http://reactiverobotics.aleksundshantu.com/sitemap.xml?tx_csseo_view=pages <http://reactiverobotics.aleksundshantu.com/sitemap.xml?tx_csseo_view=pages>

this is url
http://reactiverobotics.aleksundshantu.com/sitemap.xml?tx_csseo_view=extension&ext=news <http://reactiverobotics.aleksundshantu.com/sitemap.xml?tx_csseo_view=extension&ext=news>

**Comment by mhirdes** [comment]
There is an .htaccess protection. Please send me the access via mail to hirdes@clickstorm.de If you can, please provide me an TYPO3 backend access, too.

**Comment by anujaunds** [comment]
i resolved the problem, thanks for your help. Could you let me how i add multiple id with detailPid with like languageUids.  Because i have multiple detail page for news.

**Comment by clickstorm** [comment]
what solved the problem? 

You have to decide which news should be displayed on which detail page. Either it depends on the language or the category or whatever. Then you have to setup multiple TypoScript config, e.g.

```
plugin.tx_csseo.sitemap.extensions.newsDE < plugin.tx_csseo.sitemap.news
plugin.tx_csseo.sitemap.extensions.newsDE.languageUids = 0

plugin.tx_csseo.sitemap.extensions.newsEN < plugin.tx_csseo.sitemap.news
plugin.tx_csseo.sitemap.extensions.newsEN.languageUids = 1
```
and so on

**Comment by mhirdes** [comment]
I will close the ticket. But I am still interested what solved the problem. I have you have time, maybe you can add an answer.

**Comment by M-arcus** [comment]
@anujaunds What solved the problem?
