### ISSUE TITLE
Error when checking reference-index

### ISSUE THREAD

**Issue by nabossha** [clickstorm/cs_seo#18]
with TYPO3 7.6.11 and cs_seo installed, checking the reference-index throws this error when BE-Debug is enabled:

```
caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
   ERROR => 'Unknown column 't3ver_wsid' in 'field list'' (43 chars)
   lastBuiltQuery => 'SELECT uid,t3ver_wsid FROM tx_csseo_domain_model_evaluation WHERE 1=1' 
```
Database compare in install tool is fine, deativating the Ext solves the problem.

**Comment by mhirdes** [comment]
Please check the current dev version. There is already a fix included. https://github.com/clickstorm/cs_seo/commit/2a98dc03e3d261134446f9f6758415dbea088cd8
