### ISSUE TITLE
Question: Why Browser Title

### ISSUE THREAD

**Issue by Nemo64** [clickstorm/cs_seo#181]
If it is documented then i haven't found it.

The Browser title field seem really redundant. Or better, it makes either the Page Title or the Navigation Title redundant, depending on how you look at it.

It also creates the problem that there is no standard way of accessing the title of a page now. If you for some reason need the title, you have to adjust your extension for cs_seo.

The question is: for what? Wouldn't it be better to just extend the default typo3 functionality than to replace it?

**Comment by clickstorm** [comment]
Hi, thanks for your feedback. The browser title has specific requirements, e.g. the length, animate a user to click, integrate keywords and to add a suffix or prefix. The page title is to identificate a page in the TYPO3 backend, in our opinion.  And also it is fallback for the nav title, path segment and also the browser title. 

For the second part of your issue I think we can create a solution. Maybe we use the altPageTitle or sth. like that. 

Can you agree with this points?

**Comment by Nemo64** [comment]
so the page title is just a fallback for everything? I don't know it all seems redundant.
For the backend I recommend the user ts config `options.pageTree.showNavTitle = 1`.
For urls, well if you don't want to use your seo optimized title as url then you can just overwrite your url specifically using the realurl field.
And for navs there is the nav_title.

The thing is, I have a hard time explaining why this field exists. In the current state I can actually remove it and if you fill all other fields it would work fine.

I'm well aware that changing this now will be a mayor change.

**Comment by Nemo64** [comment]
altPageTitle may help for the technical aspect but you still for example have to create custom solr configuration if you want your search optimized title to also be in your search results.

**Comment by mhirdes** [comment]
If this is your problem, you can easily hide the browser title field, if you don't need it. I think this should work for you.
