### ISSUE TITLE
default robots.txt parameters

### ISSUE THREAD

**Issue by Nemo64** [clickstorm/cs_seo#182]
I noticed that the default robots.txt disallows `Disallow: /*?id=*` and `Disallow: /*cHash`.
This means all plugins that aren't configured in realurl must not be crawled and every page that has a non realurl url must also not be crawled.

Why? There is a canonical to prevent double urls but preventing the crawler to even access `?id=5` pages also prevents crawlers from even understanding that link. And disallowing cHash urls also seems like it'll only result in accidental index exclusion since: if the url is correctly configured, the canonical should prevent duplicate content.

**Comment by mhirdes** [comment]
Hi, as you already mentiond it is a default configuration. For our needs we don't want an id= or cHash URL in the index. Especially cHash you have in the URL by using pagination widgets. To be sure we add this in the robots.txt. 

If you don't use realURL than this would mean that all of your pages will get not to be indexed. On the other hand, if you don't use speaking URLs, you probably don't care about SEO at all. 

We have good experience with this config and in my opinion there is no need to change this. I would rather add a hint in the documentation.

What do you think?

**Comment by Nemo64** [comment]
I agree that you shouldn't have urls with `id=` or `cHash` in them. But what if you do.
 
If your workflow prevents slipups in your realurl configuration: then good for you. But others might not be too strickt and might not even know that this extension creates a robots.txt which is blocking half there seo traffic because they didn't configure news properly.

And what is the advantage of having these block rules? Letting a search engine crawl them to see that this is just an alternative url to another page shouldn't be a problem. It would be better if it were a redirect of course but that is a little more complicated.

**Comment by mhirdes** [comment]
If you do, you can modify the robots.txt content depending on your needs. It is a default config which is so integrated in a lot of projects of our own. We don't have bad experience with this. 

Again thanks for your input. I added a hint in the documentationen. But I won't change this yet, because then we would have to modify a lot of configs.
