### ISSUE TITLE
Wrong paths to backend-javascripts after upgrade to 3.0 (jquery.cs_seo.path.js and jquery.seourl.js)

### ISSUE THREAD

**Issue by nebrot** [clickstorm/cs_seo#184]
After updating cs_seo to 3.0.0/3.0.1 there are some erros in logs, the paths are not correct anymore, see screenshot. Because of this the files are not included. Seems to be introduced with this commit: https://github.com/clickstorm/cs_seo/commit/d8eb581f8d540eaf9f6af52ecf22b9832d650593

![cs_seo-bug-pfad](https://user-images.githubusercontent.com/6941112/42630227-4f783882-85d6-11e8-8aa8-34454f270b1f.png)

cs_seo: 3.0.1
TYPO3: 8.7.16

**Comment by nebrot** [comment]
It works again setting `compress = false` and `excludeFromConcatenation = true` in PermalinkWizard.php - loadJavascript(). But then i get an js-error in console: "TYPO3 is undefined".

**Comment by mhirdes** [comment]
You must delete all caches and maybe typo3temp. Should work afterwards.

**Comment by nebrot** [comment]
I already deleted whole typo3temp, fixed the folder structure after that and cleared all caches in installtool and again in top-toolbar. Same problems and warning in logs. Also tried different browsers.
By the way it's a non-composer-based installation.

**Comment by mhirdes** [comment]
Ok but we use

in https://github.com/clickstorm/cs_seo/blob/master/Classes/UserFunc/PermalinkWizard.php 

the core function
`ExtensionManagementUtility::extPath('cs_seo') . 'Resources/Public/JavaScript/';`

to add the JS.

**Comment by mhirdes** [comment]
Can you debug what this function returns?

**Comment by nebrot** [comment]
Path is correct:
ExtensionManagementUtility::extPath('cs_seo') . 'Resources/Public/JavaScript/';
=> /var/www/example.com/web/typo3conf/ext/cs_seo/Resources/Public/JavaScript/

**Comment by nebrot** [comment]
This would solve the path-problems, see an example of Core-EXT-t3editor https://github.com/TYPO3/TYPO3.CMS/blob/9c24ec5b2c1ce1a93b1a8e4a15c08e2c6c296ad8/typo3/sysext/t3editor/Classes/Form/Element/T3editorElement.php#L121:

`use TYPO3\CMS\Core\Utility\PathUtility;`

`$baseUrl = PathUtility::getAbsoluteWebPath(ExtensionManagementUtility::extPath('cs_seo')) . 'Resources/Public/JavaScript/';`

Before change:
```
Array
(
    [file] => /var/www/example.com/web/typo3conf/ext/cs_seo/Resources/Public/JavaScript/jquery.cs_seo.path.js
    [type] => text/javascript
    [section] => 1
    [compress] => 1
    [forceOnTop] => 
    [allWrap] => 
    [excludeFromConcatenation] => 
    [splitChar] => |
    [async] => 1
    [integrity] => 
)
```

After change:
```
Array
(
    [file] => /typo3conf/ext/cs_seo/Resources/Public/JavaScript/jquery.cs_seo.path.js
    [type] => text/javascript
    [section] => 1
    [compress] => 1
    [forceOnTop] => 
    [allWrap] => 
    [excludeFromConcatenation] => 
    [splitChar] => |
    [async] => 1
    [integrity] => 
)
```

After

**Comment by nebrot** [comment]
This also would solve our path-problem: `$baseUrl = 'EXT:cs_seo/Resources/Public/JavaScript/';`

See this core-example: https://github.com/TYPO3/TYPO3.CMS/blob/9c24ec5b2c1ce1a93b1a8e4a15c08e2c6c296ad8/typo3/sysext/backend/Classes/Form/FormResultCompiler.php#L214

**Comment by mhirdes** [comment]
Thanks for the PR. It's merged.
