### ISSUE TITLE
Powermail extension should be listed as a dependency

### ISSUE THREAD

**Issue by lbane** [clickstorm/cs_seo#185]
In the latest version cs_seo uses powermail functions in Classes/UserFunc/Sitemap.php, but the powermail extension is not listed as a dependency (?).

After updating to 3.0.1 I got this error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'In2code\Powermail\Utility\ObjectUtility' not found | Error thrown in file /var/www/www.dvpz.de/typo3conf/ext/cs_seo/Classes/UserFunc/Sitemap.php in line 387.`

and the news sitemap generation failed. Installing powermail resolved the issue.

**Comment by mhirdes** [comment]
Thanks a lot for the hint. I fixed it.
