### ISSUE TITLE
"TYPO3 is undefined" - jquery.cs_seo.path.js

### ISSUE THREAD

**Issue by nebrot** [clickstorm/cs_seo#187]
After updating to version 3.0.1 (and fix in #184) there is an js-error in console: "TYPO3 is undefined".
Commit: https://github.com/clickstorm/cs_seo/commit/ee270f45f3fab562ff3fd08e10b11a3c2bb14714

Wrong:
```
(function ($, TYPO3) {
    
})(TYPO3.jQuery || jQuery || $);
```

Correct:
```
(function ($, TYPO3) {
    
})(TYPO3.jQuery || jQuery || $, TYPO3);
```

TYPO3 8.7.17
Firefox 61.0.1

**Comment by mhirdes** [comment]
Thanks for the PR. It's merged.
