### ISSUE TITLE
No cached actions and cs_seo

### ISSUE THREAD

**Issue by christian-forgacs** [clickstorm/cs_seo#19]
Hi,

when I extend existing models and this model is used in a no cached action, your typoscript works only on the first execution on this page.

If you have e.g. a product detail page, you have only the first opened product seo tags in the cache. When I change in your setup.txt the [line 74](https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/setup.txt#L74) into USER_INT, it works find for me and for the other pages too without this or other extensions.

I am looking forward to your feedback.

Best regards,
Christian Forgács

**Comment by mhirdes** [comment]
Hi again,

are your products in the cache?

Kind regards,
Marc

**Comment by mhirdes** [comment]
Ok, you mentioned it already. I will test this.

**Comment by christian-forgacs** [comment]
If you have any further questions to my reports you can contact me directly over the typo3 slack group (https://forger.typo3.org/slack) > christian.forgacs

**Comment by christian-forgacs** [comment]
I can't reproduce this issue anymore.
