### ISSUE TITLE
[FEATURE] add additionalWhereClause for pages sitemap

### ISSUE THREAD

**Issue by dogawaf** [clickstorm/cs_seo#190]
Hello

It would be comfortable to have additionalWhereClause setting when generating the pages sitemap.
This setting already exists for extensions sitemap.

Would you agree if I made a pull request for that feature?

Regards

**Comment by mhirdes** [comment]
Hi, for sure. Pull requests are allways welcome.

**Comment by mhirdes** [comment]
Do youalready  know, when you will publish the pr?

**Comment by dogawaf** [comment]
I have one nearly ready but it is based on 3.0.1, and it seems that the rebase on master will be a quite long because the sitemap generation changed a bit.

**Comment by mhirdes** [comment]
If you still need this feature, please reopen the ticket. An easy way would be to override the 
 cs_seo/Resources/Private/Partials/Sitemap/PageCheck.xml partial.
