### ISSUE TITLE
[BUG] compatibility with ext:flux

### ISSUE THREAD

**Issue by grimmcreative** [clickstorm/cs_seo#191]
This Value:

```
TsConfig PID
basic.tsConfigPid (Ganzzahl)
1
The Pid where the pageTsConfig is set to extend records
```

Causes a problem with ext:flux.
The Page with the given ID will not show any FCE´s anymore.

**Comment by grimmcreative** [comment]
FLUX latest Version 9.0.1
cs_seo latest Version 3.0.1

if i change to id to a value > 1 no more issue then.

**Comment by mhirdes** [comment]
Ok and the FCE's aren't show in the backend or frontend?

**Comment by mhirdes** [comment]
Ok. I think you mean the FCE's were not shown in the new content element wizard. This works now. Maybe you can test it? Thanks for the report.
