### ISSUE TITLE
Error when editing a moved page in workspace draft mode

### ISSUE THREAD

**Issue by apartdesign** [clickstorm/cs_seo#192]
Hi,

I noticed that when I'm trying to edit a page which had been moved in a draft workspace environment then I get an error 

---
Uncaught TYPO3 Exception
Call to a member function stdWrap() on string 

Error thrown in file
.../typo3conf/ext/cs_seo/Classes/Utility/TSFEUtility.php in line 150.
---

This seems to be because Typo3 creates a Move-Placeholder. And the $GLOBALS['TSFE']->cObj results in null in the $TSFEUtility->getPageTitleSeparator() function. 

I tried to find a solution by loading the live version of the moved page but that doesn't seem right since the moved version of the page could have changes made.

Could you help me out here? Maybe point out what changes I could do?

Thanks a lot!

**Comment by mhirdes** [comment]
Hi, which Version do you user of TYPO3 and cs_seo?

**Comment by apartdesign** [comment]
TYPO3 8.7.17
cs_seo 3.0.1

**Comment by mhirdes** [comment]
To use the version overlay id works fine. Also if you edit the workspace data. Feel free to test and thanks for your report.

**Comment by ndq1** [comment]
Yes, works now.

Changes will be available in 3.0.x?

**Comment by mhirdes** [comment]
yes
