### ISSUE TITLE
Crop Title Tag Function

### ISSUE THREAD

**Issue by in-session** [clickstorm/cs_seo#195]
Small idea:

output the title tag with cropping based on the configuration setting

Clickstorm\CsSeo\UserFunc\PageTitle.php

```
// get extension configurations
$extConf = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['cs_seo']);

if ($page['tx_csseo_title_only'] == '0') {
        	$title = $this->TSFE->getFinalTitle(mb_strimwidth( $title, 0, $extConf['maxTitle'], "…"), $page['tx_csseo_title_only']);
} else {
        	$title = $this->TSFE->getFinalTitle( $title, 0, 70);
}
```

**Comment by mhirdes** [comment]
Hey. thanks for the idea. Then we also need an option to active this and to set the appending characters. if you like, you can add this and send a pull request

**Comment by tobiasgraeber** [comment]
If you toggle the checkbox "tx_csseo_title_only" to off / on (multiple times) the title is not updated correctly in the snippet preview - version 3.02 - maybe you could fix/improve that also?

**Comment by mhirdes** [comment]
Please provide a pull request if you really need this. In my opionion Google and search engines crops the title aumotically, if it is to long.
