### ISSUE TITLE
Records of extended tables are missing in the sitemap if the SEO record does not exist.

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#196]
I've extended the `news` table with a `cs_seo` configuration.
```
tx_csseo {
    1 = tx_app_news_articles
    1 {
        enable = GP:news

        fallback {
            title = title
            description = abstract
        }
    }
}
```
This enables the `SEO` tab for records of the `news` table.

Problem now is that only records for which the actual `SEO` inline record was created (and even if all fields are empty) are shown in the extension sitemap.

When there's no `SEO` inline record, the actual `news` record does not get rendered in the sitemap.

**Comment by mhirdes** [comment]
Hi, all news records should be shown. Please be sure, that the table conf etc. is correct https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/ExtendSitemap/Index.html

**Comment by thasmo** [comment]
@mhirdes Sorry, with `news` I did not mean the `news` extension, I mean a custom table named `tx_app_news_articles`. The problem I have is with custom tables which don't show up in the sitemap under the circumstances mentioned above.

**Comment by mhirdes** [comment]
did you add the field to your ext_tables.sql?

**Comment by thasmo** [comment]
@mhirdes Found the problem. The `tx_csseo` fields are actually `null`, which seems to cause them to not show up in the sitemap. Is this something the `cs_seo` would consider as fix, checking for `0` and `null`?

**Comment by mhirdes** [comment]
Why are they null? You should use this SQL statement...

```
CREATE TABLE tx_myext_domain_model_mymod (
	  tx_csseo int(11) unsigned NOT NULL default '0',
 );
```

**Comment by mhirdes** [comment]
It's fixed in the branch 3x

**Comment by vvprodan** [comment]
Hello!
I had the following problem, the SEO field did not appear in the news records, although I have already set up a lot of websites with SEO in the news, but this is my first time
Kernel version 8.7.22
What could be the problem?
Even if we looked in the tx_news config, the tx_csseo field did not appear. Thank you so much before!
