### ISSUE TITLE
pathsegment in TCA is required field, even when ignored

### ISSUE THREAD

**Issue by andre-spindler** [clickstorm/cs_seo#197]
TYPO3: 8.7.19
realurl: 2.4.0
cs_seo: 3.0.2

EXT:cs_seo makes field pages:tx_realurl_pathsegment a required field.
In all cases, and therefore ignoring pages:tx_realurl_exclude.
Please change this - this behaviour confuses our editors...

**Comment by mhirdes** [comment]
Hi. You can disable this in the extension manager settings https://docs.typo3.org/typo3cms/extensions/cs_seo/Administrator/ExtensionManagerConf/Index.html#basic-enablepathsegment

**Comment by andre-spindler** [comment]
You didn't got the point.
I don't mean to disable the automatic filling of the pathsegment field.
The ticket is about the configuration of the pathsegment field, not it's content.
It doesn't make sense to make the filed a required field if it is disabled for the current page.
