### ISSUE TITLE
Meta-Robots Tag index, follow

### ISSUE THREAD

**Issue by mindbreaker** [clickstorm/cs_seo#198]
By default, the Meta-Robots tag is only output by the extension if the user sets a value here in the backend. If nothing is set, the tag itself is not output either. 

If the Robots tag is not set, it would be better if it is output with index,follow.

**Comment by mhirdes** [comment]
Hi. I answered this question multiple times also here https://docs.typo3.org/typo3cms/extensions/cs_seo/Administrator/TroubleShooting/Index.html 

Quote from Google: The default values are "index, follow" (the same as "all") and do not need to be specified.

https://support.google.com/webmasters/answer/79812?hl=en

Kind Regards,
Marc
