### ISSUE TITLE
Meta tags for FE_USERS

### ISSUE THREAD

**Issue by gvv1401** [clickstorm/cs_seo#199]
I have 2 pages: list of FE_USERS records and user details.
I want to configure META tags for details page. For example: FirstName LastName | SiteName.
But I'm getting error: 
An exception occurred while executing 'SELECT `sys_language_uid` FROM `fe_users` WHERE (`uid` = ?) AND ((`fe_users`.`deleted` = 0) AND (`fe_users`.`disable` = 0) AND (`fe_users`.`starttime` <= 1538485860) AND ((`fe_users`.`endtime` = 0) OR (`fe_users`.`endtime` > 1538485860)))' with params [2]: Unknown column 'sys_language_uid' in 'field list'

I found of reason of this problem. This is line #318 in HeaderData.php:
$lang = $this->getLanguageFromItem($currentItemConf['table'], $currentItemConf['uid']);
when I replaced it to:
$lang = 0
then all works fine.

I want correct solution of this issue. How? Help pls.

TYPO3: v.8.7.18
CS_SEO: v.3.0.2

My TSconfig:
tx_csseo {
        # new index and table name of the model
        10 = fe_users

        # if the get parameter is set in the URL the cs_seo properties will be shown
        10.enable = GP:person

        # if the model already has fields like title etc. define them as fallback
        10.fallback {

            # cs_seo title field fallback = mymod title field
            title = first_name

            # cs_seo description field fallback = mymod description field
            description = last_name
        }

        # enable evaluation for news
        10.evaluation {
                # additional params to initialize the detail view, the pipe will be replaced by the uid
                # getParams = &tx_myext_pi1[controller]=MyController&tx_myext_pi1[action]=MyAction&tx_myext_pi1[mymod]=|

                # detail pid for the current records, only if set the table will be available
                detailPid = 96
        }
}

**Comment by mhirdes** [comment]
Hey, thanks for the hint. I fixed this in branch 3x and master.
