### ISSUE TITLE
"Fatal error: Call to a member function printTitle() on null" when editing a newly created Shortcut

### ISSUE THREAD

**Issue by ericstumper** [clickstorm/cs_seo#2]
Hi,

I just tried to create a shortcut to a page via the list module inside a sysfolder. This sysfolder is inside a parent page that has the cs_seo typoscript added to its template. The extension in general is working as expected.
Although when I try to edit this shortcut after creation I get the following error:

```
Fatal error: Call to a member function printTitle() on null in /Applications/MAMP/htdocs/typo3_gny/typo3_src/typo3_src-7.6.9/typo3/sysext/frontend/Classes/Page/PageGenerator.php on line 1104
```

I could successfully reproduce the error on a team member's system (also TYPO3 7.6.9). When I deactivate cs_seo the edit dialogue opens as expected, so it must have something to do with the extension.

Thanks in advance for helping me out or fixing this should it be a bug.

**Comment by mhirdes** [comment]
Hi,

thanks for your advice. Please try the current github version. The SEO features are there not enabled for shortcuts, because there are not necessary for them. 

Maybe you can give me feedback if it works for you.

**Comment by ericstumper** [comment]
Shortcuts seem to work fine with the 1.1.1-dev version. But now editing a real page inside my sysfolder throws an exception:

```
Fatal error: Call to a member function getTypoScriptSetup() on null in /Applications/MAMP/htdocs/typo3_gny/typo3_src/typo3_src-7.6.9/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php on line 133
```

**Comment by mhirdes** [comment]
Strange, maybe you have to clear the whole cache in the install tool?

**Comment by mhirdes** [comment]
And on other pages outside the sys_folder it works?

**Comment by ericstumper** [comment]
I just rechecked. I cannot edit any page's options with cs_seo active, just the shortcut. Flushed all cache and cleared typo3temp just in case.

**Comment by mhirdes** [comment]
Strange. In this line it checks what configurationManager is used. Should work. I can't reproduce the error. Which PHP version do you use?

**Comment by ericstumper** [comment]
Currently 5.6.10.

**Comment by mhirdes** [comment]
It's hard for me to reproduce this error. I test it with PHP 5.5 and 7.6. Everything is ok. Or do you use any other extension wich extends the page properties? The problem seem to be, that the configurationmanager does not initalize the correct type. I check it again.

**Comment by mhirdes** [comment]
Ok, I use now the specific BackendConfigurationManager. I updated the GitHub Version. Use the commit 39975684873b87e1099093fece64697d7f4c3e2c. Please let me know, if the error still occures.

**Comment by ericstumper** [comment]
This seems to work as expected for editing both shortcuts as well as pages! Will you be able to push a new release to the TER soon? Thanks for your help!

**Comment by mhirdes** [comment]
Yes I will update the TER version soon. Thanks a lot for your cooperation.
