### ISSUE TITLE
Missing keywords for extended models

### ISSUE THREAD

**Issue by christian-forgacs** [clickstorm/cs_seo#20]
Hello again,

keywords are not implemented for extended models but exists in the inline element.

Best regards,
Christian Forgács

**Comment by mhirdes** [comment]
Hi Christian,

thanks for your feedback. The focus keyword you can already set. But you are right, until now there is no evaluation of this. But in the future there will be a view in the seo module where the evaluation of each record could be shown or maybe directly while editing a record. But I can't say now when this feature will be available. If you don't need it so quickly, maybe you can hide the field. 

Kind regards,
Marc

**Comment by davdenic** [comment]
Hi in the Yoast article it's written:

> Update August 2015: unfortunately we had to drop the suggestion drop down of our Yoast plugin, since Google shut down the autocomplete API that was needed for this feature.

source: https://yoast.com/focus-keyword/

Does it make any sense to keep the focus keyword field visible in the BE? Thanks

**Comment by mimoat** [comment]
Yes, it does make sense. The article states that the yoast team had to drop the "sugesstion drop down" menu . This feature doesn't exist in cs_seo.

**Comment by mhirdes** [comment]
Currently the feature looks if the keyowrd is set in the title, the description and the content. If there is a need to extend this, than we could do this. Who dosen't need this feature, can hide the field and remove the evaluator in the extension manager settings.

**Comment by mhirdes** [comment]
This feature is available in 2.0
