### ISSUE TITLE
If a Page is "disabled" but user uses the "preview" the page title and meta-settings are NOT set

### ISSUE THREAD

**Issue by tobiasgraeber** [clickstorm/cs_seo#204]
As the title says.
If a page is "disabled" but you view the "preview" as an TYPO3 Admin user, you excpect the Page Title / SEO Values to be respected in the preview also. But instead, the Page-Title/Description seems to be set to the root-Item/Default.

If you "enable" (publish) the page instead, it works.

Tested on TYPO3 8.7 with Branch dev-3x and (dont know if relevant: vhs v.5.1.*, flux: 8.1.*, fluidpages 4.1.* and fluidcontent 5.2.*)

Could you please try to reproduce this or check if the page access/restriction state is properly respected and maybe fix that?

Tanks!

**Comment by mhirdes** [comment]
Hi, I don't use fluidpages... I tested it with TYPO3 8.7 and cs_seo dev-3x. If you deactivate fluidpages, does it then works?

**Comment by tobiasgraeber** [comment]
Thanks, working in 3x know. I dont know what changed between but ..okay. Are there any plans for a new release, containing all the latest changes and maybe backports from TYPO3 9 features/fixex, but especally for TYPO3 8.7 LTS (imprived snippet preview (see above) for example etc.) ??

**Comment by mhirdes** [comment]
A new release I will publish if I got feedback on open tickets. There will be no backport. If you miss sth. in the 3x release, please tell me.
