### ISSUE TITLE
sitemap.xml: empty news-sitemap is generated also if no news entrys are present and news-extension is installed but not configured in tx_csseo configuration

### ISSUE THREAD

**Issue by tobiasgraeber** [clickstorm/cs_seo#206]
even if you dont have any news in your system yet and also if you dont configured "extensions" news in your ts there is a link generated in the sitemap.xml like this:

http://domain.local/?type=655&tx_csseo_view=extension&ext=news

Below this url, youl find an empty sitemap like this:

`<urlset><url><loc/></url><url><loc/></url><url><loc/></url><url><loc/></url></urlset>`

Suggestion:
- check if any PUBLISHED news are in the system and only then generate news-sitemal / or add a setting to configuration to enable/disable the news-sitemap generation at all ?

**Comment by mhirdes** [comment]
Mmhh. I am with u, but then we have to check in the sitemap index view for every sub sitemap if there are records. Furthermore in cs_seo v4 the sitemap.xml generation is removed, because you can do this within the TYPO3 v9 LTS core. Can u live with the current solution until v9?
