### ISSUE TITLE
Extension not working in 9.5

### ISSUE THREAD

**Issue by matin73** [clickstorm/cs_seo#208]
Error when installing:
(1/1) #1482394401 UnexpectedValueException
Missing "type" in TCA of field "['pages']['seo_title']['config']".

And:
Loading ext_localconf.php of extension "cs_seo" failed

**Comment by kraemer-igroup** [comment]
I don't have the UnexpectedValueException with TYPO3 9.5.1. But cs_seo should definde the core extension "seo" as dependency, else `\TYPO3\CMS\Seo\Canonical\CanonicalGenerator` etc. in ext_localconf.php can not be resolved.

**Comment by mhirdes** [comment]
seo is now also in the ext_emconf.php a dependency
