### ISSUE TITLE
Unnecessary wrap for twitter meta tags?

### ISSUE THREAD

**Issue by derghostface** [clickstorm/cs_seo#209]
I don't get it why the meta tags for twitter:creator and twitter:site are wrapped with <meta |/>. With that in TYPO3 9.5 you get following output:
```
<meta name="twitter:creator" content="&lt;meta name=&quot;twitter:creator&quot; content=&quot;@&quot; /&gt;" />
<meta name="twitter:site" content="&lt;meta name=&quot;twitter:site&quot; content=&quot;@&quot; /&gt;" />
```
Changing the wrap to "@|" it works as expected. I also added "required=1" so that the meta tags are not shown when there is no content defined.

**Comment by mhirdes** [comment]
Thanks a lot for your report.
