### ISSUE TITLE
Setting a custom canonical URL changes the open graph URL too

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#210]
When using the `Clickstorm\CsSeo\UserFunc\HeaderData::beforeMetaTagsCreatedForRecords` signal/slot to change `$metaData['canonical']` to a custom URL it also changes the `og:url`:

```php
$metaTags['og:url'] = $this->printMetaTag('og:url', $canonical, 1);
```

Is this an intended behavior?

**Comment by thasmo** [comment]
After some research it seems to me, that the FB scraper follows the canonical URL anyway, so setting `og:url` to teh value of `canonical` looks good. Are there any other reasons?

**Comment by mhirdes** [comment]
Yes, that is the intended behavior. Do you see a problem here?

**Comment by thasmo** [comment]
@mhirdes Looks good to me! Thanks for your reply.
