### ISSUE TITLE
Enable snippet preview for my custom title field in my custom extension model

### ISSUE THREAD

**Issue by Georgyge** [clickstorm/cs_seo#211]
Hii,
  I am using cs_seo 2.3.4 in my typo3 8.7.20 version. I have to use seo into my custom extension model. I added the pageTsconfig datas into my pageTsconfig field in root page. Now the title and description field of seo is from my custom extension.
I need to have snippet preview window near to my title field. I had used the configuration
```
'heading1' => [
            'exclude' => false,
            'label' => 'LLL:EXT:tnt_eberhard_references/Resources/Private/Language/locallang_db.xlf:tx_tnteberhardreferences_domain_model_references.heading1',
            'config' => [
                'type' => 'input',
                'size' => 30,
                'eval' => 'trim,required',
                'wizards' => [
                    '_POSITION' => 'bottom',
                    'previewWizard' => [
                        'type' => 'userFunc',
                        'userFunc' => 'Clickstorm\\CsSeo\\UserFunc\\PreviewWizard->render'
                    ]
                ]
            ],
        ],
```

but this is not working. How to add snippet preview window to my custom title field in my custom extension?

**Comment by mhirdes** [comment]
When you do the following steps https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/ExtendExistingModel/Index.html

Then you get an Seo IRRE-Elemet automatically. There is also the preview shown. Currently it is not implemented to show the preview without the other seo fields.
