### ISSUE TITLE
wrong/invalid id set to typoscript variable "languageUids" disables typo3 page caching completely

### ISSUE THREAD

**Issue by tobiasgraeber** [clickstorm/cs_seo#213]
i recently discovered the following side-effect which leads to an completely disabled page cache. i dont know exactly why this happens but, if you configure an id in the list of "languageUids", that is NOT availiable in the system or invalid, than (enable admin Panel and have a look into the "info" section) the TYPO3 page caching is NOT working any more.

I think the reason for this might be that cs_seo tries to get data in background for the page from an (as statet) not availeable language id, but this (of course) fails and by that the page caching is not possible any more...

I think there has to be a place in cs_seo´s code the languageUids configured in TS are used and that is where additional checks may be needed, if those IDs are really availeable and valid in the TYPO3 system and if one of the IDs profides by TS is not availeable, the fallback handling / return handling should be improved to fallback gracefully or - just dont side effect caching (should always work..., even if cs_seo fails on languageUids i think...).

maybe you could check that, please?! Thanks in advance!

**Comment by mhirdes** [comment]
Which versions of TYPO3 and cs_seo do you use?

**Comment by mhirdes** [comment]
Can't reproduce this. With cs_seo 3.x I got a cache entry. With cs_seo 4.x there is no languageUid option.
