### ISSUE TITLE
How to display a list with an keywords field?

### ISSUE THREAD

**Issue by gvv1401** [clickstorm/cs_seo#216]
Hello!
How to display a list with a keywords field? It's possible?
![default](https://user-images.githubusercontent.com/10170885/51262077-47292100-19ba-11e9-8c61-a36ebbd38299.png)

Regards, Vadym.

**Comment by mhirdes** [comment]
Hi it would be possible, but the meta keywords are not relevant for SEO because they will be ignored by the search engines. Or do I miss a point? https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html
