### ISSUE TITLE
Don't show hreflang for hidden tx_news records on detail page

### ISSUE THREAD

**Issue by neotrace** [clickstorm/cs_seo#217]
Hi, in a multilangage 8.7 installation I have just discovered that if translations of news records are hidden (for example IT and FR news records hidden, but DE and EN active ), on the detail pages of the active news records (DE & EN) a hreflang to IT and FR news records is still inserted in the source.  This results in a problem for me since the links point to pages without any content on them.

In my opinion, these two languages should be missing from hreflang, since they are hidden. I tried modyfing hrefLang.ts, but with no success. There you have a condition that hreflang only gets inserted when tx_csseo_canonical // tx_csseo_no_index // content_from_pid is not set. I tried to expand to news  records but without success.

I think it would be a nice addition if this condition would respect the hidden status of news records. Any chance you can make this happen? Any info on how to accomplish this would be appreciated.

Thanks, Steffen

**Comment by mhirdes** [comment]
Hi, we respect the hidden state of the news record. I've testet this again, with cs_seo 3.0.3 and TYPO3 8.7.24. In https://github.com/clickstorm/cs_seo/blob/3x/Classes/UserFunc/HeaderData.php Line 200 you'll see, that we use the function $GLOBALS['TSFE']->sys_page->getRecordOverlay();. This function respects also the hidden state. Be sure, that you are not logged in the TYPO3 backend at the same time. Maybe you have the option set to show hidden records.

**Comment by neotrace** [comment]
Hmm, that is strange. I wonder why this is then? We always have 7 hreflangs to all our languages in the source for every news record, regardless if the language is hidden or not. Normally the hidden ones should be missing or am I thinking wrong?

This results in many hreflang errors in sistrix since the linked pages with hidden news translations result in a 404 page. We set the sys_language_mode to strict just for these detail pages to achieve this. Might this be related?
