### ISSUE TITLE
SQL Error when creating new domain record

### ISSUE THREAD

**Issue by kurtwithslc** [clickstorm/cs_seo#218]
if i create a new domain record i get following error:
SQL error: 'Unknown column 'tx_csseo_robots_txt' in 'field list'' 

it is not possible to store the record 

Typo3 9.5.4

**Comment by PascaleBeier** [comment]
Sounds like you need to run a DB compare

**Comment by kurtwithslc** [comment]
i use cs_seo 4.01
db_compare says: ... Good job, nothing to do!
all caches are cleared, no change

which procedure should create 'tx_csseo_robots_txt' for table 'sysdomain' ?
