### ISSUE TITLE
[BUG] sitemap.xml - Multidomain Environment 8.7.x

### ISSUE THREAD

**Issue by grimmcreative** [clickstorm/cs_seo#224]
I am using a Multidomain Environment for 2 Languages.
Sitemap.xml shows correct URLs of Domains, but in Sitemaps of particular domain wrong path are rendered. L=0 shows URL Path of L=1

**Comment by mhirdes** [comment]
Hi, sry for the late response. If you wan't to we can take a look together to your TYPO3. Therefore write a slack message or mail.
