### ISSUE TITLE
Task : clean og:image typoscript

### ISSUE THREAD

**Issue by dogawaf** [clickstorm/cs_seo#225]
https://github.com/clickstorm/cs_seo/blob/c2cae0fd4a2d4b6c959f251a7a9687d12c5d0bab/Configuration/TypoScript/Setup/Meta/openGraph.typoscript#L14

In the og:image typoscript, the userFunc does not exists anymore in php code.

**Comment by mhirdes** [comment]
Thanks for the hint. It's fixed
