### ISSUE TITLE
BUG: Auto-Scrolling in Module "SEO"?

### ISSUE THREAD

**Issue by tobiasgraeber** [clickstorm/cs_seo#226]
If i go to Module "SEO" and choose a root Page and set "deep" to "5" (or any other value) i can see all pages and their browser titles and descriptions and so on...

BUT:

If i start scrolling down the list by mouswheel or even klicking the up/down arrows after some scrolling the lists starts SCROLLING AUTOMATICALLY down all the entys. Could you please fix that?

Also it would be nice, if the List (id="csSeoGrid") is always as heigh as the viewport allows. currently it´s set to "377px" by inline style (or js?).

Thanks in advance!

**Comment by mhirdes** [comment]
Hi. Which Version of cs_seo, TYPO3 and Browser do you use?
