### ISSUE TITLE
PHP error in CanonicalAndHreflangHook

### ISSUE THREAD

**Issue by dogawaf** [clickstorm/cs_seo#227]
The method getLanguageFromItem does not exists in CanonicalAndHreflangHook.

```
Call to undefined method Clickstorm\CsSeo\Hook\CanonicalAndHreflangHook::getLanguageFromItem()
```

I don't understand the purpose of the code that should call getLanguageFromItem(), so I can't propose a fix.
On my website, sys_language_mode is strict, so I simply commented out the call to getLanguageFromItem, thus the canonical respects the page language id.

TYPO3 9.5
cs_seo 4.1.0

**Comment by derhansen** [comment]
Same problem here. The method `getLanguageFromItem()` does not exist and results in a PHP fatal

**Comment by mhirdes** [comment]
Thanks for the hint. It's fixed.
