### ISSUE TITLE
Canonical tag should not be output on a page with noindex

### ISSUE THREAD

**Issue by mindbreaker** [clickstorm/cs_seo#228]
If you set a page to `noindex` the canonical tag should be removed. 

> This is also where the guide that you shouldn't mix noindex & rel=canonical comes from: they're very contradictory pieces of information for us. 
[Source:](https://www.seroundtable.com/google-noindex-rel-canonical-confusion-26079.html) John Mueller(Google)

**Comment by mhirdes** [comment]
If you mean for pages, then there exists a ticket for TYPO3 9 https://forge.typo3.org/issues/86569
