### ISSUE TITLE
PHP warning in TYPO3 8.4.1 page properties

### ISSUE THREAD

**Issue by t3easy** [clickstorm/cs_seo#23]
I get a PHP warning while I try to open the page properties.

#1476107295: PHP Warning: file_get_contents(/home/httpd/vhosts/domain.tld/httpdocs/typo3/web/typo3conf/ext/cs_seo/Resources/Private/Templates/PreviewWizard.html): failed to open stream: No such file or directory in /home/httpd/vhosts/domain.tld/httpdocs/typo3/vendor/typo3/cms/typo3/sysext/backend/Classes/Template/DocumentTemplate.php line 1279 (More information)

## Environment
TYPO3 8.4.1 composer mode 
PHP 7.0.11
cs_seo 1.7.0

**Comment by mhirdes** [comment]
Hi,

I tested it again and everything works fine. Do you use https in frontend or backend?

Kind regards,
Marc

**Comment by mhirdes** [comment]
Cleared the cache and the error appeared :sweat_smile: Fix is online https://github.com/clickstorm/cs_seo/commit/759d7fec1da24dc3d91c7fd89635205f68e0cfe1 . Maybe you could test it, too.

**Comment by t3easy** [comment]
Yes works now. thx!
