### ISSUE TITLE
inPageModule doesn't find custom evaluation partials

### ISSUE THREAD

**Issue by Narfsn** [clickstorm/cs_seo#230]
I'm using cs_seo 3.1.0 with TYPO3 8.7.24 but i guess it affects the current version too.

I wrote an custom validator based upon: https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/ExtendEvaluation/Index.html 

It works inside the "Module" view but it seems the "evaluation.inPageModule" encounters an error due to not being able to find the additional Evaluators Partials. As soon as i enter Page>Columns it tries to load "/typo3conf/ext/cs_seo/Resources/Private/Partials/Results/Fulltitle.html" which doesn't exist.

As it seems the inPageModule is rendered via Clickstorm\CsSeo\Hook\PageHook and Line 97 doesn't find the the current module/plugin settings (You could set whatever you want as the "extension" the result ist always the same. CsSeoHook doesn't exist as an extension key anyways?)

```
$tsSetup =
    $configurationManager->getConfiguration(
        ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK,
        'CsSeoHook'
    );
$layoutPaths = $tsSetup["view"]["layoutRootPaths"] ?: $layoutPaths;
$partialPaths = $tsSetup["view"]["partialRootPaths"] ?: $partialPaths;
```

It works if i'm using CONFIGURATION_TYPE_FULL_TYPOSCRIPT (which returns everything but the $extensionName parameter doesn't seem to work anyway?):

```
$tsSetup =
    $configurationManager->getConfiguration(
        ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT
    );
$layoutPaths = $tsSetup["module."]["tx_csseo."]["view."]["layoutRootPaths."] ?: $layoutPaths;
$partialPaths = $tsSetup["module."]["tx_csseo."]["view."]["partialRootPaths."] ?: $partialPaths;
```

Did i miss to add something in Typoscript / Setup or could this be a problem?

**Comment by mhirdes** [comment]
Thanks for your hint. It's fixed. What is the task of your evaluator? Maybe we can integrate it in cs_seo.
