### ISSUE TITLE
Title tag and meta description

### ISSUE THREAD

**Issue by wasimahmed19** [clickstorm/cs_seo#232]
Hi,

I want to override the default values of the title tag and meta description.
In the extension configuration even after increasing the values. Still, the default values are reflected.
Please let me know how to extend the character limit in CS_SEO extension.
Have given the values as 80 and 201
![CS_SEO1](https://user-images.githubusercontent.com/50316802/57212296-e1ac7f00-7000-11e9-9900-be1d0e02905b.jpg)
Still getting the default values
![CS_SEO2](https://user-images.githubusercontent.com/50316802/57212401-3c45db00-7001-11e9-8c5f-0df06023222c.jpg)
![CS_SEO3](https://user-images.githubusercontent.com/50316802/57212402-3c45db00-7001-11e9-8c50-cda0d37bdd85.jpg)

**Comment by mhirdes** [comment]
Which version do you use of cs_seo, TYPO3 and PHP?

Did you clear the system cache afterwards? You need to do this. Otherwise the TCA will not be rebuild.
