### ISSUE TITLE
Unconsistent record overlay and no versionOL

### ISSUE THREAD

**Issue by dogawaf** [clickstorm/cs_seo#235]
Hello

When getting a record from the database with a SQL query, the overlay and versionOL must be applied in frontend context, with `$GLOBALS['TSFE']->sys_page->getRecordOverlay()` and `$GLOBALS['TSFE']->sys_page->versionOL()`

In [Service/MetaDataService.php#L142](https://github.com/clickstorm/cs_seo/blob/bf8f1f7c7bad5c126b288af4016c0f12a0c0b555/Classes/Service/MetaDataService.php#L142), call to `getRecordOverlay` must be done in any case (TYPO3 will take care of overlaying or not) and call to `versionOL` must be added.

I can make a PR if your are agree.

**Comment by mhirdes** [comment]
ok, imo the versionOL is not so important, because Google and get the live version. But if you will  add a PR I can apply your changes.

**Comment by dogawaf** [comment]
For versionOL, I have users that wan't to "preview" changes in seo fields on the draft workspace.

I will make a PR.

**Comment by dogawaf** [comment]
I submited two PR: one for master, and the same fix for 3.x.
