### ISSUE TITLE
Breadcrumb is empty on treeLevel 0

### ISSUE THREAD

**Issue by kraemer-igroup** [clickstorm/cs_seo#236]
Googles testing tool for structured data (https://search.google.com/structured-data/testing-tool) gives an error on the "root" page because "itemListElement" is empty. I think the output of an empty breadcrump should be omitted.

My suggestion would be to add a typoscript condition "[tree.level > 0]" within "Configuration/TypoScript/Setup/structuredData.typoscript" around "page.footerData.656".

Or you could add a condition
`if (count($rootline) < 2) {
    return '';
}`
in "Classes/UserFunc/StructuredData.php" after line 117.

**Comment by mhirdes** [comment]
Hey, bugfix is online. Feel free to test.
