### ISSUE TITLE
Wrong TS condition leads to exception

### ISSUE THREAD

**Issue by derghostface** [clickstorm/cs_seo#237]
The condition `[getTSFE().beUserLogin]` in some scenarios leads to an exception, because there is no check on getTSFE() before:

> "expression":"getTSFE().beUserLogin", "exception":"RuntimeException: Unable to get a property on a non-object. in
htdocs\/vendor\/symfony\/expression-language\/Node\/GetAttrNode.php:73\nStack trace:\n#0

In our case this lead to an error on a detail view of an extbase plugin on a very high frequented site. So I think this is critical and should be fixed as soon as possible.

The correct condition which solves this issue is:
`[getTSFE() && getTSFE().isBackendUserLoggedIn() == 1]`

**Comment by mhirdes** [comment]
Thanks for the hint. Fix is integrated.
