### ISSUE TITLE
Evaluation in BE doesn't work

### ISSUE THREAD

**Issue by davdenic** [clickstorm/cs_seo#24]
Hi
the evaluation doesn't works, it spin for a while and then it says 
"No results. Press update."
How can I debug it? 
Is it compatible with fluid_styled_content and fluidcontent, fluidpages, flux, vhs?
Thanks

**Comment by mimoat** [comment]
this helped me a lot: (the 5 steps) [https://docs.typo3.org/typo3cms/extensions/cs_seo/Administrator/Index.html]
also good to know:
it won't work, if your installation is e.g. htpasswd protected.
for debugging purposes:
Open chrome dev tools and watch the eID Script (Network -> XHR) when clicking of update. If there are errors in the response you would notice it there (for page module). good luck!

**Comment by davdenic** [comment]
Hi 
major problem is i don't get any error.
the 5 steps are just 4, i don't find it in the scheduler tasks.
i'm on nginx, my dev server is password protected, but i tested also without password protection and it doesn't work.
chrome console shows no error for this XHR
typo3/index.php?ajaxID=CsSeo%3A%3Aevaluate&ajaxToken=aeac388a5f2e9b91976b92a3e577a5a7044c2c68
response 200
thanks

**Comment by mimoat** [comment]
ah okay,
you can try to activate the scheduler task:
1. add new scheduler class
2. select "extbase-command-controller-task" as task
3. input a number as frequency (i used 3600)
4. CommandController-Command: select CssSeo Evaluation "update" from List
5. Hit Save
6. Run that Scheduler task.

I don't know if this steps are necessary.

Also be sure to set a correct (and reachable domain record!) - So if you have e.g.:
www.mymachine.dev - it should be "crawlable" by your TYPO3 dev machine

**Comment by mhirdes** [comment]
Hi,

is the frontend of the page avalibale in public? If you have a .htaccess protection you have to allow the server where TYPO3 runs to call the frontend. So add the IP from the server to the .htaccess file https://docs.typo3.org/typo3cms/extensions/cs_seo/Administrator/Index.html . 

Does this solve the problem?

Kind regards,
Marc

**Comment by davdenic** [comment]
Hi 
I could solve it on my dev removing password protection, i will test on live since last time it didn't worked, thanks

**Comment by mhirdes** [comment]
Which Version of PHP, TYPO3, cs_seo do you use? I also wrote you on Slack. If you like to we could chat there first, to find the problem.
