### ISSUE TITLE
Hreflang x-default value

### ISSUE THREAD

**Issue by ohanel** [clickstorm/cs_seo#240]
When extension hooks into the generating header hreflang tags, the original typo3 functionality for generating the `'<link rel="alternate" hreflang="x-default" href="' . $firstLanguageLink . '"/>'` is not preserved.
Awaited behaviour is to generate also that x-default hreflang language.

**Comment by mhirdes** [comment]
Hi. You work with TYPO3 9.5? Not allways is the default languange in TYPO3 also the x-default. Image you have a german default language and an english translation. The x-default would be in this case the english translation, not the default language. My suggestion would be to add a new setting, where you can define the sys_language_uid of the x-default. What do you think about this?

**Comment by ohanel** [comment]
Hi. I am currently working with Typo3 9.5.8. The solution you suggest seems logical. But in my opinion, the logic of generating x-default hreflang language in your extension should match the current "logic" of Typo3. Which is as described above, the first language in the array.
If you go with the new option solution, it should be probably part of siteconfig.yml? Because x-defaults can differ per site node. Thanks!

**Comment by mhirdes** [comment]
ok, added the x-default like the core. If you like, you can test it.

**Comment by flolanger** [comment]
Hi. I would like to reopen this issue because I think we need a option to set the x-default value. As @mhirdes mentioned already, there are a lot of TYPO3 instances where english is not the sys default language. But if users with an unrecognizable language enter your site, it's more logical to direct them to your english site rather than to your default language site (which might not be english).

TDR; I would like to get an option to set the x-default value on my preferred language (default can still be core behavior).

**Comment by clickstorm** [comment]
@flolanger you can now change the x-default in the site configuration. !Important. If the x-default equals not the default language cs_seo will generate the canonical and hreflang for pages. We only add URL parameters that are defined in [FE][additionalCanonicalizedUrlParameters]. You can activate this also for the case that your x-default equals the default lanugage in the extension manager configuration. I am looking forward for your feedback. Please test the branch 4x

**Comment by devxpoint** [comment]
Hi, in TYPO3 11 and cs_seo 7.3 the x-default selectbox in the site configuration shows only my first (default) language: German.
English (ID:1) is not present in the select box.
How can I achive this, to make English the x-default language?

<img width="507" height="276" alt="Image" src="https://github.com/user-attachments/assets/8ab60bb1-bcc5-4398-a0c1-6046844f7d22" />
