### ISSUE TITLE
TYPO3 PageTitle API won't work with cs_seo installed. 

### ISSUE THREAD

**Issue by AKaravas** [clickstorm/cs_seo#242]
I am using TYPO3 v9.5.8 in composer mode and i am implementing the PageTitle API.
I am using everything correctly, i get the wished title on my page, but if i activate the cs_seo, the PageTitle API won't work anymore. I have something like that:

```
config.pageTitleProviders {
    someIdentifier {
        provider = Vendor\ExtName\Helper\MyOwnPageTitleProvider
        before = record
        after >
    }
    seo {
        before >
        after = someIdentifier
    }
    altPageTitle {
        after = seo
        before >
    }
}
```

but seo overrides that as well. I checked the TypoScript Object Browser and it seems that a setting with the name and value `[titleTagFunction] = Clickstorm\CsSeo\UserFunc\PageTitle->render` is present. 

If use that on my TypoScript `config.titleTagFunction >` then the page title works again, but not with the suffix.

I do not know if that is the reason, but something overrides the current settings, which makes the extension not that useful at the moment.

Best regards,

**Comment by mhirdes** [comment]
Hey. You are correct. As long at there is a hard coded wrap in the core with the sitename, we cannot use the pageTitleAPI. https://forge.typo3.org/issues/86573 
So it is not possible to exclude the sitename from long site titles. If you have records with own browser titles, you can easily set them up for cs_seo https://docs.typo3.org/p/clickstorm/cs_seo/4.1/en-us/Developer/ExtendExistingModel/Index.html

**Comment by clickstorm** [comment]
Fixed in cs_seo 5
