### ISSUE TITLE
feature: add a checkbox in page to exclude it from sitemap

### ISSUE THREAD

**Issue by davdenic** [clickstorm/cs_seo#246]
Hi, I have some pages I'd like to exclude from sitemap but i don't want use the "no index" checkbox. 

For example when I have an extension with the show action the page that contains the plugin goes in the sitemap. for example:

/news (it's ok contains news list)
**/news/detail (i'd like to exclude this)**
/news/detail/this-is-a-news (this is ok)

Even an exclude list in TS could be enough.
It could be also interesting to have a setting to exclude "not in menu" pages.

Thanks

**Comment by mhirdes** [comment]
you can set the checkbox noindex on the detail page and extend your records easily https://docs.typo3.org/p/clickstorm/cs_seo/4.1/en-us/Developer/ExtendExistingModel/Index.html , then also the noindex will be overrwritten if the news is not set the noindex.
