### ISSUE TITLE
Unwanted parameters in url (canonical/hreflang)

### ISSUE THREAD

**Issue by bluhmsysteme** [clickstorm/cs_seo#248]
If you clear cache and open a page in frontend with a random parameter, lets say:

https://www.mysite.com/about-us/?randomparameter=true

then this parameter is stored and appears in all canonical tags and hreflang attributes. Even if you open https://www.mysite.com/about-us/ afterwards, still the parameter is present in canonical and hreflang.

Is this behaviour normal?

**Comment by mhirdes** [comment]
Hi. Wich TYPO3 and cs_seo Version do you use?

**Comment by clickstorm** [comment]
You can use the setting in the extension manager conf useAdditionalCanonicalizedUrlParametersOnly. Then only the parameter of [FE][additionalCanonicalizedUrlParameters] will be used. Otherwise all parameter can be added. The problem exist also in the core https://forge.typo3.org/issues/90936
