### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by cmichael-de** [clickstorm/cs_seo#249]
Evaluation works only on root page. On subpages I get the following error:

![image](https://user-images.githubusercontent.com/6968063/65593467-d26aa580-df90-11e9-9a10-dc492921b985.png)

**Comment by Gitsko** [comment]
I have the same problem, my error message is:

Not Updated
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by PascaleBeier** [comment]
Please ensure that the Server is able to call the URL configured in the Site configuration. Most likely a configuration error. 

For starters, try pinging the site from the Command Line and with cURL and see if that works. Provide more information and cURL output if you think this is an error on cs_seo end.

**Comment by cmichael-de** [comment]
I can call the URL in Browser http://p458230.mittwaldserver.info/die-praxis. How can I get "the URL configured in the Site configuration". Here is my Site configuration - do you mean the "Entry Point" or the Site Identifier?

![image](https://user-images.githubusercontent.com/6968063/66895438-1a5e7480-eff3-11e9-92eb-dfc1587bb857.png)

Thanks a lot!

**Comment by PascaleBeier** [comment]
Entry point should be set to "http://p458230.mittwaldserver.info/" instead of "/" - please try again

**Comment by cmichael-de** [comment]
Perfect! It'sworking! 

And a `curl -I -L  http://p458230.mittwaldserver.info/` via SSH got me a `HTTP/1.1 200 OK`

Thanks a lot!!
