### ISSUE TITLE
is it possible to move some values into constants?

### ISSUE THREAD

**Issue by davdenic** [clickstorm/cs_seo#25]
Hi
in the evaluators i see values into the code like

`		if($count > 0 && $count < 7) {
			$state =  self::STATE_GREEN;
		} elseif ($count > 6) {
			$state = self::STATE_YELLOW;
		}`
(from H2Evaluator)

I think it could be useful to move that 7 and 6 outside in a constant, maybe in the ext_conf_template.txt, so if we want to use another value we don't have to change the code.
for what i know the h2 limit it's not written in stone.
what do you think?

the same in other evaluators, for example:

`		return $this->evaluateLength($title, 40, 57);`
(from the title evaluator)
Ok maybe this is a bit more "written in stone" :)
Thanks

**Comment by davdenic** [comment]
Note:
some values like maxTitle, maxDescription are yet in the ext_conf_template.txt but not used in the evaluators code.

**Comment by mhirdes** [comment]
Hey thanks for the feedback. I had this already on my todo list. Now it's online. Maybe you can test it and give me feedback. New TER Version will also be available soon. Maybe you can test it before.
