### ISSUE TITLE
PagesUpdater and MySQL strict_mode

### ISSUE THREAD

**Issue by opi99** [clickstorm/cs_seo#253]
> 'UPDATE `pages` `u` SET `u`.`no_index` = `u`.`tx_csseo_no_index` WHERE (`no_index` = ?) OR (`no_index` IS NULL)' with params [""]: Truncated incorrect DOUBLE value: ''

The no_index field is marked as INTEGER, so you can't compare it with an empty string

**Comment by mhirdes** [comment]
I didn't found a satisfying solution until now. Either I set manually which are numeric or check the column types, but they are not only integer or string, also smallint etc. Do you have a good idea?

**Comment by opi99** [comment]
No, set them manually is enough IMHO

**Comment by mhirdes** [comment]
finally did it
