### ISSUE TITLE
PagesUpdater leads to data loss 

### ISSUE THREAD

**Issue by opi99** [clickstorm/cs_seo#254]
The PagesUpdater tries to migrate every single field by calling `DatabaseUtility::migrateColumnNames` which foreach over every entry in the `$columnNamesToMigrate` array. This is done by using the same QueryBuilder for every column without using the reset() function. This leads to multiple `->set()` calls (which can be called multiple times to add more SQL set statements). So you have in the first round following SQL Statement:

> UPDATE `pages` `u` 
> SET `u`.`seo_title` = `u`.`tx_csseo_title`, 
> WHERE (`seo_title` = '') OR (`seo_title` IS NULL)

But in the second round you get

> UPDATE `pages` `u` 
> SET `u`.`seo_title` = `u`.`tx_csseo_title`, 
>     `u`.`canonical_link` = `u`.`tx_csseo_canonical`, 
> WHERE (`canonical_link` = '') OR (`canonical_link` IS NULL)

and so on. Which leads eventually to data loss in the seo_title field.

**Comment by mhirdes** [comment]
I wrote a functional test for this, no data is getting lost. Or do I miss a point?

**Comment by opi99** [comment]
For example:

u.seo_title is already set and u.canonical_link is empty, then u.seo_title gets overwritten by u.tx_csseo_title in the second round, which should only update the canonical link.

**Comment by mhirdes** [comment]
Got it. Fix is online.
