### ISSUE TITLE
Fallback to Parent Object

### ISSUE THREAD

**Issue by develth** [clickstorm/cs_seo#255]
Hi,

i had an similar  Ticket (#194) but this time it changes:

I made an extension to view E-Papers. (Backend-)Users can upload a PDF and create pages for an Outline (1:n). It should be Possible, that the Users can create SEO definitions for each page - when no pagedefinition is given, the parent definition should be taken (if available).

Reason: We want to Share a single PDF-Page on e.g. Facebook with the special Informations (Image, Title), if no Information is given the Information of the parent object should be shared.

So i have two URLs:

    tx_ep_d[controller]=Ep&tx_ep_d[action]=detail&tx_ep_d[ep]=ID
    tx_ep_d[controller]=Ep&tx_ep_d[action]=detail&tx_ep_d[ep]=ID&tx_ep_d[page]=ID

ep = E-Paper Object-ID, page the Page ID.

I made following TS Config:

```
2 = tx_ep_domain_model_page
2.enable = GP:tx_ep_d|page
2.evaluation {
   getParams = &tx_ep_d[controller]=Ep&tx_ep_d[action]=detail&tx_ep_d[ep]=&tx_ep_d[page]=|
}
3 = tx_ep_domain_model_ep
3.enable = GP:tx_gbepaper_default|ep
3.evaluation {
  getParams = &tx_ep_d[controller]=Ep&tx_ep_d[action]=detail&tx_ep_d[ep]=|
}
```
And: It works pretty well :)
But if the Page Object does not have an SEO definition, the definition of the parent Object is ignored and everthing is empty.

How to get this case working?

Thanks & best regards
Thomas

**Comment by mhirdes** [comment]
Which TYPO3 and cs_seo version do you use?

**Comment by develth** [comment]
4.2.0

**Comment by mhirdes** [comment]
There is no fallback option. If you set the parameter tx_ep_d[page] in your URL, the Metadata will be generated from the page object. You have to use the fallback options, so that title and description are not empty. 

If tx_ep_d[ep] is set, this parameter will be used. Also here use the fallback options in the TsConfig.
