### ISSUE TITLE
Couldn't get URL

### ISSUE THREAD

**Issue by Terminator81** [clickstorm/cs_seo#257]
when I do the validation I get the above mentioned error

what do I have to do to fix this?

**Comment by mhirdes** [comment]
May this can help you https://docs.typo3.org/p/clickstorm/cs_seo/4.2/en-us/Administrator/TroubleShooting/Index.html

**Comment by Terminator81** [comment]
no i think the problem exists since Typo3 version 9.5.11 or the current version of CS_SEO

**Comment by Terminator81** [comment]
any news?
can someone confirm the bug?

**Comment by mhirdes** [comment]
In our TYPO3 systems and current cs_seo versions everything is ok, please read the TroubleShooting section. What do you want to evaluate, pages or records?

**Comment by Terminator81** [comment]
in my htacces i have added 

order allow,deny
allow from *serverip*
allow from all

still does not work
![grafik](https://user-images.githubusercontent.com/16563785/70371448-819df400-18d3-11ea-8bb3-21afe058b27a.png)

**Comment by czimmer-kiag** [comment]
We have the same problem under TYPO3 CMS 9.5.11 and cs_seo 4.2.0, but we found a solution for it.

After changing the site configuration (we changed the value of field "Einstiegspunkt" on tab "Allgemein" from "/" to "https://domain.tld/"), it works for us.

**Comment by Terminator81** [comment]
thanks it works for me too :)
