### ISSUE TITLE
Move og:image files to persistent folder

### ISSUE THREAD

**Issue by LimeUwe** [clickstorm/cs_seo#258]
Hi,

we encountered the problem, that files which got used in link posts on facebook disappaered in the social streams. The reason was, that the og:images which were generated by cs_seo are placed in the _proccessed_ folders. Unlike other social networks, Facebook DOES NOT cache these files on their servers. If those image files get purged by TYPO3, e.g. within the install tool, they won't be shown on facebook anymore. Using the "Facebook Batch invalidtor" is supposed to fix this, but it does not work.

To prevent this, we adjusted the image genaration code in the HeaderData Class, so the images get generated in another place:

/**
     * Return an URL to the scaled image
     *
     * @param string $originalFile uid or path of the file
     * @param array $imageSize width and height as keys
     *
     * @return string
     */
    protected function getScaledImagePath($originalFile, $imageSize)
    {
        $conf = [
            'file' => $originalFile,
            'file.' => [
                'height' => $imageSize['height'],
                'width' => $imageSize['width']
            ]
        ];
        $imgUri = $this->cObj->cObjGetSingle('IMG_RESOURCE', $conf);

        /*** BEGIN HACK - move image to persistent directory ***/

        // check for folder
        if(!file_exists(PATH_site.'fileadmin/user_upload/persistent-og-images')) {
            mkdir(PATH_site.'fileadmin/user_upload/persistent-og-images');
        }

        // move og:image file to persistent folder
        if(file_exists(PATH_site.$imgUri) && $imgUri !== '') {
            $pathInfo = pathinfo($imgUri);
            // check file path string vs. object id
            if(is_int($originalFile)) {
               $newImageUri = "fileadmin/user_upload/persistent-og-images/og-image-".$originalFile.'-'.$imageSize['width'].'x'.$imageSize['height'].'.'.$pathInfo['extension'];
            } else {
               $newImageUri = "fileadmin/user_upload/persistent-og-images/".$pathInfo['basename'];
            }
            rename (PATH_site.$imgUri, PATH_site.$newImageUri);
        }

        $imgUri = $newImageUri;

        /*** END HACK - move image to persistent directory ***/

        $conf = [
            'parameter' => $imgUri,
            'forceAbsoluteUrl' => 1
        ];

        return $this->cObj->typoLink_URL($conf);
    }

For a more gerenal solution, the file path might be changed a bit.
Right now, we use it in a TYPO3 7 environment, for a future compatibility with TYPO3 v10, the PATH_site constant must be adjusted to something like 
\TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/'

Best regards,
Uwe

**Comment by mhirdes** [comment]
Hi. Thanks for your hint. Since TYPO3 v9 the og images were generated by the core.

**Comment by mhirdes** [comment]
If you can, please open a ticket on TYPO3 forge for this.
