### ISSUE TITLE
"Trenner" + cs_seo module = TYPO3 error in BE

### ISSUE THREAD

**Issue by medarob** [clickstorm/cs_seo#259]
Hi,

when I click on a "Trenner" page type in the pagetree and want to see the seo infos by clicking on the cs_seo module in the backend I get this error:

![grafik](https://user-images.githubusercontent.com/33951787/70527896-43136e00-1b4d-11ea-8a4c-9ab7fd847372.png)

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function stdWrap() on string | Error thrown in file /var/www/typo3/web/typo3conf/ext/cs_seo/Classes/Utility/TSFEUtility.php in line 238. Requested URL: https://domain.tld/typo3/index.php?route=%%2Fweb%%2FCsSeoMod1%%2F&token=--AnonymizedToken--&id=114`

It would be better to show a page with the info: "No SEO info available and necessary for this page type." (or something similar).

**Comment by mhirdes** [comment]
Please check your allowed doktypes for evaluation in the extension manager settings for cs_seo.
![13-12-_2019_15-30-02](https://user-images.githubusercontent.com/915162/70807282-870caa00-1dbd-11ea-8cc2-91287cc609fe.png)
