### ISSUE TITLE
locallang label as title suffix/prefix?

### ISSUE THREAD

**Issue by davdenic** [clickstorm/cs_seo#26]
Hi
i've seen that you are using the sitetitle from the TS template in your TS code. 
is it possible use a locallang label as title suffix/prefix instead the template sitetile?
The sitetitle doesn't work well with translated suffix/prefix.
For that reason i'm used to have it in locallang something like:

`		title = TEXT
		title {
			data = LLL:myext/Resources/Private/Language/locallang.xlf:titleSuffix
			dataWrap = {page:tx_csseo_title // page:title}|
		}
`

Hope you like the idea,
What do you think?

note: 
it's not just TS, the title is generated also in Classes/Utility/TSFEUtility.php:144

`    /**
     * @var string $title
     * @var bool $title
     *
     * @return string
     */
    public function getFinalTitle($title, $titleOnly = false) {
    	if($titleOnly) {
	        return $title;
    	}

        $siteTitle = $this->getSiteTitle();
        $pageTitleFirst = $this->getConfig()['pageTitleFirst'];
        $pageTitleSeparator = $this->getPageTitleSeparator();

        if($pageTitleFirst) {
            $title .= $pageTitleSeparator . $siteTitle;
        } else {
            $title = $siteTitle . $pageTitleSeparator . $title;
        }
        return $title;
    }`

Thanks

**Comment by mhirdes** [comment]
Hey there is a new settings in TS Setup `plugin.tx_csseo.sitetitle` where you can override the sitetitle. If you like, you can test this and give me feedback.
