### ISSUE TITLE
Bug: typeNum 654 not found on root page in different language on root page

### ISSUE THREAD

**Issue by flolanger** [clickstorm/cs_seo#263]
Hi,

if you edit the **page properties** on the **root page** in a **different language** (not the default one), you get the following error **under the seo_title field**:

`No page with typeNum 654 found. Please include the TypoScript from the 'cs_seo' Extension in your root TypoScript.`

Even if your TypoScript is included correctly. This happens only on the root page and only in a different language than the default one.

**TYPO3 version used**: 9.5.14
**cs_seo version used**: 4.2.1

It seems like a bug in the extension.

**Comment by clickstorm** [comment]
@flolanger  please test the current branch 4x

**Comment by clickstorm** [comment]
@TODO error with TYPO3 11.5.7
