### ISSUE TITLE
Unable to generate url

### ISSUE THREAD

**Issue by pagliaso** [clickstorm/cs_seo#264]
Hello,

I am using Typo3 9.5.13 and your nice extension, and I have had this problem for a few times.

Basically after performing some maintenaince on my web: delete cache, completing pending upgrades, checking db intergrity, etc, I sometimes come back to the front end to find an error message that the site is not available:

`unable to generate a url for the named route "web_csseomod1" because this route was not found.`

I was able to get to the install tool, and delete the cache again and get rid of the problem, although I also deleter the cache on the browser, and wouldn't be able to tell which onde solved it.

The error log I am getting on the backend is this one:

` Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476050190: Unable to generate a URL for the named route "web_CsSeoMod1" because this route was not found. | TYPO3\CMS\Backend\Routing\Exception\RouteNotFoundException thrown in file /home/domain/public_html/t3kit/web/typo3/sysext/backend/Classes/Routing/UriBuilder.php in line 103. Requested URL: https://www.domain.es/ `

I am doing anything wrong, or how I could get ride of this route, that is always causing troubles on my site, and I am not aware of what it is.

Many thanks and kind regards from Spain,

Alberto

**Comment by clickstorm** [comment]
Hola Alberto,

this error occures when the extension was set to inactive without clearing the cache. So if you remove the extension from your packagestates, you also have to clear the cache. Otherwise the backend still tries to reach the cs_seo backend module.

Does this help you?

Kind regards,
Marc

**Comment by pagliaso** [comment]
Hola Marc,

Many thanks for your kind and helpful reply.

Yes, that helps.

Kind regards,

Alberto
