### ISSUE TITLE
HrefLangGenerator::generate() has been removed in TYPO3 v10.3

### ISSUE THREAD

**Issue by pascal20997** [clickstorm/cs_seo#265]
Hey,

you are using the HrefLangGenerator inside the CanonicalAndHreflangHook (https://github.com/clickstorm/cs_seo/blob/master/Classes/Hook/CanonicalAndHreflangHook.php#L194). The used method generate() has been removed without previous deprecation during TYPO3 v10.3 (https://github.com/TYPO3/TYPO3.CMS/commit/639c7e0fd8edb3f185c8c2a96a48344dd652954e#diff-cbeee12dddcc1f171933d7710b054ffcL75-R51) and replaced by __invoke() magic method.

Greetings,
Pascal

**Comment by mhirdes** [comment]
Thanks for you hint. Is resolved
