### ISSUE TITLE
cs_seo blocked Update from TYPO3 8 to 9

### ISSUE THREAD

**Issue by fjacobi** [clickstorm/cs_seo#266]
Hej,

during a Upgrade cs_seo blocked the upgrade wizards with errors, unfortunately I did not copy the exact error message, but the reason was the following:
SqlExpectedSchemaHook is executed, which calls ConfigurationUtility::getTablesToExtend(), which calls BackendUtility::getPagesTSconfig($tsConfigPid).

That one uses a fixed query to read the slug, but at that point during the upgrade, the slug field is not there yet, since the upgrade just started.
That leads to a block of all other upgrade wizards until one deactivates cs_seo during the process.

**Comment by clickstorm** [comment]
A fix is available

**Comment by fjacobi** [comment]
Couldn't exactly reproduce the setup, but restored a DB snapshot and the upgrade wizard ran through.

Thanks!
