### ISSUE TITLE
Table not found Exception

### ISSUE THREAD

**Issue by froemken** [clickstorm/cs_seo#267]
Hello,

I'm using cs_seo in version 4.2.1.
I have an absolute empty TYPO3. No tables in DB. Nothing.
When I visit the InstallTool to create the needed TYPO3 tables I get following error:

`Doctrine\DBAL\Exception\TableNotFoundException
An exception occurred while executing 'SELECT `pid`, `uid`, `title`, `doktype`, `slug`, `tsconfig_includes`, `TSconfig`, `is_siteroot`, `t3ver_oid`, `t3ver_wsid`, `t3ver_state`, `t3ver_stage`, `backend_layout_next_level`, `hidden`, `starttime`, `endtime`, `fe_group`, `nav_hide`, `content_from_pid`, `module`, `extendToSubpages` FROM `pages` WHERE (`uid` = ?) AND (`pages`.`deleted` = 0)' with params [1]: Table 'db.pages' doesn't exist`

In Backtrace I have found this line:

`/var/www/html/public/typo3conf/ext/cs_seo/Classes/Utility/ConfigurationUtility.php line 73`
-> BackendUtility::getPagesTSconfig($tsConfigPid);

Why do you want to generate TSconfig in InstallTool?!

Please find another solution. IMO the Installtool should always be runable.

Stefan

**Comment by clickstorm** [comment]
Hi. A fix is available. Looking forward to your feedback.

**Comment by froemken** [comment]
First part solved, but now it crashes at this position:

`$rootLine = BackendUtility::BEgetRootLine($tsConfigPid, '', true);`

in SqlExpectedSchemaHook::addMetadataDatabaseSchemaToTablesDefinition()

**Comment by clickstorm** [comment]
also fixed in the current master. We'll use a YAML configuration instead of the page TSconfig
