### ISSUE TITLE
Wrong initialization of TSFE for snippet preview in extension

### ISSUE THREAD

**Issue by akiessling** [clickstorm/cs_seo#270]
I am trying to get the snippet preview running in TYPO3 10.4 for EXT:news.
In \Clickstorm\CsSeo\Form\Element\SnippetPreview::getBodyContent a fake TSFE is initialized, my preview box only showed an error message, that no TypoScript could be loaded for the target page.

```
$TSFEUtility = GeneralUtility::makeInstance(
    TSFEUtility::class,
    $pageUid,
    (int)$data['sys_language_uid']
);
```

`$data['sys_language_uid']` is not an integer, but an array with only one entry: `"0" => "0"`
So after changing that casting to `int)current($data['sys_language_uid'])` i get a preview.
I'm not sure when that changed, and it IMHO does not really make sense to pass an array, but i remember to have seen that data behaviour before during a 9.5 upgrade.

TYPO3 10.4.6
cs_seo 5.0.0

**Comment by clickstorm** [comment]
Thanks for the hint. Will be fixed in the new version.
