### ISSUE TITLE
Client error in any language prevents the display of results

### ISSUE THREAD

**Issue by cyMarvin** [clickstorm/cs_seo#271]
I know this is a quite unusual and more or less temporary setup but I think some others might encounter a similar problem.

We use cs_seo 5.0.1 with TYPO3 10.4.7.
Only the default language is available in the frontend - the other languages, which are already configured, are redirected to another subdomain (e.g. example.org/en -> en.example.org).

Therefore the content analysis for the page translation throws an error and shows a flash message.

![flashmessage](https://user-images.githubusercontent.com/26959854/92903655-870c0a00-f422-11ea-85e6-144c2fdedcf0.png)

When the AJAX call gets any content in the response body (e.g. the flash message) the page does not reload - even though the analysis was successful for the default language and I wish to see the result for that.

I would like to see it reloading automatically instead of me just reloading the page after every single analysis. 
![reload](https://user-images.githubusercontent.com/26959854/92904527-3ba62b80-f423-11ea-8c5f-3b73475d24bd.png)

If there is a reason why this should not happen, I would appreciate the extension to send a custom HTTP header when fetching the frontend page so I can exclude those requests from my redirect (like i did locally for now).

![custom_header](https://user-images.githubusercontent.com/26959854/92905163-b66f4680-f423-11ea-9aa3-9088d48cca09.png)

![redirect](https://user-images.githubusercontent.com/26959854/92905210-c424cc00-f423-11ea-9553-9a3b4de6909c.png)

**Comment by mhirdes** [comment]
Hi, I added the header in the current master. To understand you correctly you would like to have the location.reload outside of the `if(repsonse.length)` ?

**Comment by cyMarvin** [comment]
Hi, thank you for that!
Yes, in my opinion the reload should be done no matter the response length.
The response is supposed to contain only flash messages if any.
Reloading the location won't affect those and ensures showing the results of the default language analysis.

**Comment by mhirdes** [comment]
done :)

**Comment by cyMarvin** [comment]
Works for me.
Thank you very much. :)
