### ISSUE TITLE
Query Builder Exception occures in Backend Module | TYPO3 9.5.22

### ISSUE THREAD

**Issue by danmoebius** [clickstorm/cs_seo#273]
Hi, 

we are getting an Exception in Backend-Modul. While your method "setSysPageWhereClause" overwrites the value of "where_groupAccess" to an empty value, TYPO3 failures on building Where-Clause in PageRepository on line 363. The Method of QueryBuilder "andWhere" expects one argument. But zero passed in, because of the empty value. 

Could you test bug, please? 

TYPO3: 9.5.22
cs_seo: 4.3.0

![Exception_BackendModul](https://user-images.githubusercontent.com/5362336/95201264-f554aa00-07df-11eb-8f53-7c6d94314c1a.png)

best regards

**Comment by mhirdes** [comment]
Was a bug in doctine
