### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Site\Entity\PseudoSite::getConfiguration() in 4.x

### ISSUE THREAD

**Issue by tomhatzer** [clickstorm/cs_seo#274]
Hi there!

We've currently got the same issue like here https://github.com/clickstorm/cs_seo/pull/268 - but the fix is not available in the latest 4.x release.

Would it be possible to put this fix also inside the 4.x release branch and tag a new release for it?

Thank you very much!

Best wishes
Tom

**Comment by mhirdes** [comment]
Thanks for the pull request
