### ISSUE TITLE
[BUGFIX] Breadcrumb should prefer "nav_title"

### ISSUE THREAD

**Issue by SventB** [clickstorm/cs_seo#276]
The structured data breadcrumb uses field "title" from the page record, but it should use the field "nav_title", because of two reasons:

1. The breadcrumb is a navigation
2. The title of the root page is often s.th. "ugly", e.g. "root1" or "www.mysite.de" or "Congratulations" (in "The official Introduction Package")

Just write this in StructuredData.php:
```php
- 'name' => $page['title'],
+ 'name' => $page['nav_title'] ? $page['nav_title'] : $page['title'],
```

**Comment by mhirdes** [comment]
Thanks for your feedback. Fix is online.
