### ISSUE TITLE
JavaScript Assets in Backend-Preview

### ISSUE THREAD

**Issue by YannikSMYLIE** [clickstorm/cs_seo#278]
If I use cs_seo and usercentrics extension the "usercentrics request window" is displayed in the edit form of pages.
Seems like assets added by the AssetCollector are loaded with ajax.

You can stop this behaviour by adding 
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS'] = [];`
to TSFEUtility.php (I added it before preparePageContentGeneration around line 159.

But I'm not sure if it has any other effects that I'm unaware of.
Unfortunately I'm also not able to do a pull request ;)

**Comment by mhirdes** [comment]
Which TYPO3 and cs_seo do you use?
