### ISSUE TITLE
Missing tab SEO in news in some installations

### ISSUE THREAD

**Issue by Ugluuglu** [clickstorm/cs_seo#279]
Hello, 
i can not figure out why in some installations i see the tab SEO in the news article and in others not. In one setup with  TYPO3 9.5.24 and cs_seo 4.3.1 the tab is visible in the other not.  
In TYPO3 10.x i can not see the tab as well.

**Comment by mhirdes** [comment]
Hey,
they are not autoatmically shown for news. You have to configure this 

for cs_seo < 6 with page TSconfig 
https://docs.typo3.org/p/clickstorm/cs_seo/5.0/en-us/Developer/ExtendExistingModel/Index.html 

or cs_seo >= 6 with YAML 
https://docs.typo3.org/p/clickstorm/cs_seo/6.1/en-us/Developer/ExtendExistingModel/Index.html
