### ISSUE TITLE
Overwrite Meta Tags

### ISSUE THREAD

**Issue by cyrotek** [clickstorm/cs_seo#280]
Hey everyone, 

in your Documentation you write "As in TYPO3 v9 LTS recommended, we use the MetaTag Api to add our Meta Tags. You can override them easily. Take a look at the TYPO3 Core API.". 
I've a scenario where I need to overwrite the Meta Tags by cs_seo, however, it aint working. It seems like the Meta Tags will be added after my controller action.

Any hints?

**Comment by mhirdes** [comment]
Hey. 

We offer you to extend your records with SEO Options https://docs.typo3.org/p/clickstorm/cs_seo/6.1/en-us/Developer/ExtendExistingModel/Index.html 

If an editor fills them out, we need to add them in the frontend. Therefore we overrite on detail pages the meta tags.

If you have further questions, you can also write me on slack.
