### ISSUE TITLE
Canonical and hreflang

### ISSUE THREAD

**Issue by mindbreaker** [clickstorm/cs_seo#282]
**Problem**
If a page has a canonical to another page, that page should not get a hreflang reference. Since hreflang references should always point to a non-canonicalized page. 

**Possible Solution**
A solution could be that if a page has a canonical to another page, the hreflang tag is decativated here.

Sources
- https://twitter.com/JohnMu/status/969825377001537536
- https://www.portent.com/blog/seo/implement-hreflang-canonical-tags-correctly.htm

**Comment by mhirdes** [comment]
I fully agree. A fix will be available soon.

**Comment by mhirdes** [comment]
Fix is in master and branch 6x

**Comment by mindbreaker** [comment]
Thanks.
