### ISSUE TITLE
Database error after update to 6.4

### ISSUE THREAD

**Issue by simonkey** [clickstorm/cs_seo#283]
Version: 6.4
DB: MariaDb 10.3/10.4
Typo3 Version: 10.4.14

After upgrading to 6.4 detail pages return in the following error.
```
An exception occurred while executing 'SELECT `t`.`sys_language_uid`, `t`.`uid` FROM `tx_custom_table`, `tx_custom_table` `t` LEFT JOIN `tx_csseo_domain_model_meta` `m` WHERE (`m`.`uid_foreign` = `t`.`uid`) AND (`m`.`tablenames` = ?) AND ((`m`.`no_index` = 1) OR (`m`.`canonical` <> ?)) AND ((`t`.`l18n_parent` = ?) OR (`t`.`uid` = ?)) AND (((`tx_custom_table`.`deleted` = 0) AND (`t`.`deleted` = 0) AND (`m`.`deleted` = 0)) AND ((`tx_custom_table`.`hidden` = 0) AND (`t`.`hidden` = 0) AND (`m`.`hidden` = 0)) AND (`m`.`starttime` <= 1623747600) AND ((`m`.`endtime` = 0) OR (`m`.`endtime` > 1623747600))) GROUP BY `m`.`uid`' with params ["tx_custom_table", "", 249, 249]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (`m`.`uid_foreign` = `t`.`uid`) AND (`m`.`tablenames` = ?) AND ((`m`.`n...' at line 1
```

The problem seems to be the LEFT JOIN without an ON-condition in https://github.com/clickstorm/cs_seo/blob/6x/Classes/Service/AbstractUrlService.php#L131. 

Solution: The `m.uid_foreign = t.uid` in the WHERE-clause could be used as the ON-condition and resolves the error.

**Comment by mhirdes** [comment]
How about a TYPO3 update to 10.4.17?

**Comment by simonkey** [comment]
Ok, it works after an upgrade to 10.4.17. 

Maybe the should be an dependency in the composer.json about the TYPO3 version?

**Comment by mhirdes** [comment]
I can do so, but I don't know the correct minor version where this fixed. I'd add version ^10.4.17?

**Comment by mhirdes** [comment]
Thanks. I added it to the branch 6x
