### ISSUE TITLE
JSON-LD field not shown for custom records

### ISSUE THREAD

**Issue by creationell** [clickstorm/cs_seo#284]
We've written an extension with multiple entities that we want to extend with cs_seo metadata. While it is really easy to add the relation and database field as described [here](https://docs.typo3.org/p/clickstorm/cs-seo/7.0/en-us/Developer/ExtendExistingModel/Index.html), we've experienced a bug with the JSON-LD field. The text field is not rendered at all (see screenshot below, I also checked the HTML markup - it's empty). For pages, the field is rendered as expected.

![image](https://user-images.githubusercontent.com/31882731/122255734-b4fd0e00-cece-11eb-871f-e04932943113.png)

- TYPO3 10.4.16
- cs_seo 6.4.0

**Comment by mhirdes** [comment]
Hey. Thanks for report. I have a TYPO3 10.4.17. Does it work there? In my setup it works as it should

![17-06-_2021_08-26-55](https://user-images.githubusercontent.com/915162/122343359-e82eb400-cf45-11eb-8e67-e832fa49ecc5.png)

**Comment by creationell** [comment]
Okay, found the problem:

In [JsonLdElement.php](https://github.com/clickstorm/cs_seo/blob/master/Classes/Form/Element/JsonLdElement.php) you do sth. like this:

```php
if (isset($GLOBALS['TSFE'])) {                    
   $siteTitle = $TSFEUtility-&gt;getSiteTitle();                    
   $pageTitleSeparator = $TSFEUtility-&gt;getPageTitleSeparator();                    
   $config = $TSFEUtility-&gt;getConfig();
        if ($table == 'pages') {                        
             $GLOBALS['TSFE']-&gt;config['config']['noPageTitle'] = 0;
             $GLOBALS['TSFE']-&gt;generatePageTitle();
             $pageTitle = static::getPageRenderer()-&gt;getTitle();
              // get page path                        
              $path = $TSFEUtility-&gt;getPagePath();
              
         } else {
             // other records
```

In other words: you're heavily relying on TSFE being present for pages records. For other records (the `else` part), you're not using TSFE at all. Thus, it should be no problem to move the outer if inside the inner. 


While I'm writing: Thanks for the quick reply. I will check with 10.4.17 as well.

**Comment by creationell** [comment]
Still the same behavior on 10.4.17

May I contribute a PR?

**Comment by mhirdes** [comment]
I don't get it, why it is a problem in your setup and not in mine. Where are your records stored? Is there a site config and a TypoScript Template? 

A PR is allways welcome.

**Comment by creationell** [comment]
I've justz opened the PR. My guess is that the TSFE is available in this context randomly - in your case it is, in mine it's not.

**Comment by mhirdes** [comment]
Sry for the late response. You're right, to load the TSFE is here not necessary. Thank you a lot. The changes will be included in the next release.
