### ISSUE TITLE
misplaced sitemap configuration

### ISSUE THREAD

**Issue by codeKerl** [clickstorm/cs_seo#286]
I'm using cs_seo in version 6.4 in Typo3 v10.4.17, in combination with systems 'seo' extension.
The fields for sitemap.xml configuration in page configuration are pushed from SEO tab to SoMe tab.

Is this 'wanted' behaviour? 
sitemap.xml in my opinion ist SEO not SoMe.

**Comment by mhirdes** [comment]
Thanks a lot for the hint. We disable these fields in our setup, so we didn't recognize this behaviour. With the next release this will be fixed. Until then you could use the master or 6x branch.
