### ISSUE TITLE
Configuration getting ignored

### ISSUE THREAD

**Issue by Michi01** [clickstorm/cs_seo#290]
Hey,

i have a problem with the configuration
https://docs.typo3.org/p/clickstorm/cs_seo/main/en-us/Configuration/Social/Index.html
if i set something like this in the typoscript template, its not working. Neither in the form or in the site the settings are visible.
Is there any way to the the default creator and site? So that the authors dont have to enter it all the time. 

plugin.tx_csseo.social.twitter.creator = @asdasdasd
plugin.tx_csseo.social.twitter.site = asdasdasd

it would be enough if the form is prefilled if the default values

I'am on typo 10.4.25 and cs_seo 6.4.1

**Comment by mhirdes** [comment]
Hey,

I checked it again and it works. Please make sure, that you use TypoScript Constants, no setup.

Otherwise you can contact me on slack and we'll find the error together.

**Comment by Michi01** [comment]
Thank you, i did not use TypoScript Constants, so this was the issue. :) Thank you!
