### ISSUE TITLE
How to use with custom doctype´s?

### ISSUE THREAD

**Issue by slowhand11** [clickstorm/cs_seo#291]
Ho can i add the Content Analysis to a custom PageType?

**Comment by thasmo** [comment]
You're probably looking for [`evaluationDoktypes`](https://docs.typo3.org/p/clickstorm/cs-seo/main/en-us/Administrator/ExtensionManagerConf/Index.html#doktypes).

**Comment by slowhand11** [comment]
Ah, i did not see it, thanks very much!
