### ISSUE TITLE
Raise composer version to 11.5

### ISSUE THREAD

**Issue by lucmuller** [clickstorm/cs_seo#292]
ext_emconf.php says that the extension is compatible with typo3 11.5 but composer.json says it depends en typo3 11.2 thus blocking composer upgrade process.

please raise requirements to TYPO3 11.5.
also, in ext_emconf.php raise version to version 7.2.2 as extension is published on master branch.

**Comment by mhirdes** [comment]
The constraint in the composer.json for TYPO3 is "^11.2". It will be satisfied by versions matching >=11.2.0 <12.0.0-0. So there should be now problem.

The master version is 7.2.2-dev whicht is also correct.

**Comment by mhirdes** [comment]
You can also contact me on TYPO3 Slack to find a solution

**Comment by lucmuller** [comment]
On packagist, I read : 

Requires
    [typo3/cms-core](https://packagist.org/packages/typo3/cms-core): ^11.2
    [typo3/cms-seo](https://packagist.org/packages/typo3/cms-seo): ^11.2
    
Doesn't that means that extension requires TYPO3 version 11.2.x this requirement, won't match TYPO3 12 nor 11.5, or am I missing something ?
not quite used to use composer at the moment.

**Comment by mhirdes** [comment]
Maybe this helps you to understand: https://madewithlove.com/blog/software-engineering/tilde-and-caret-constraints/

^11.2 means  >=11.2.0 <12.0.0-0.

you can also check it here:
https://jubianchi.github.io/semver-check/#/
