### ISSUE TITLE
[TYPO3 9.5.30] Checking wrong Page Id on root page

### ISSUE THREAD

**Issue by oliverschloebe** [clickstorm/cs_seo#295]
Hey there,

we're still using TYPO3 v9 on a client project (upgrading is not yet possible) and `cs_seo` 4.3.1 and just ran into a problem when running the "SEO analysis". The script seems to check the wrong page id as seen here:

![TYPO3 error](https://i.postimg.cc/FFPCLfPP/image-2022-06-02-001.jpg)

It's a multi-language project with german being the default language yet the script seems to be checking the wrong page id (=825) which is the english translation of the root page.

Any idea?

Thank you!

**Comment by mhirdes** [comment]
Hey, 

if you contact me on slack, we can take a look together on your project.

But next week I am in hollidays. The week after would be ok.
