### ISSUE TITLE
'TSFEUtility' bug in File PageTitle.php

### ISSUE THREAD

**Issue by fennecgit** [clickstorm/cs_seo#299]
Please include the following error in your error list:

**Core: Exception handler (WEB): Uncaught TYPO3 Exception: syntax error, unexpected 'TSFEUtility' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) | ParseError thrown in file xxxx....ext/cs_seo/Classes/UserFunc/PageTitle.php in line 18.**

This error occurs only with php 7.3 and cs_seo v 6.6.0.

Thank you in advance for correcting the error.

**Comment by mhirdes** [comment]
Fixed in current master
