### ISSUE TITLE
PHP 7.4 dependency in v6.6.0 (for TYPO3 v10)

### ISSUE THREAD

**Issue by ohader** [clickstorm/cs_seo#301]
https://github.com/clickstorm/cs_seo/blob/43e9c842a3be4e204a4a8280a274330d9e5e7088/Classes/UserFunc/PageTitle.php#L18

TYPO3 v10 has a minimum requirement of PHP 7.2. The mentioned code location above implicitly requires PHP 7.4 and fails on systems running lower PHP versions.

```bash
find . -type f -name '*.php' -exec php72 -l {} \;

PHP Parse error:  syntax error, unexpected 'TSFEUtility' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ./Classes/UserFunc/PageTitle.php on line 18

Parse error: syntax error, unexpected 'TSFEUtility' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ./Classes/UserFunc/PageTitle.php on line 18
Errors parsing ./Classes/UserFunc/PageTitle.php
```

Related commit: 66b9253d

**Comment by ohader** [comment]
Resolved with PR #302

**Comment by mhirdes** [comment]
Thanks for the pull request. PHP 7.2 is not supported since 2 years, but you are right, TYPO3 v10 supports it.

**Comment by ohader** [comment]
> Thanks for the pull request. PHP 7.2 is not supported since 2 years, but you are right, TYPO3 v10 supports it.

Sure, but there are OS distributions and web hosting providers out there that still actively support PHP 7.2.
Thanks for responding so quickly! :+1:

**Comment by herzogkienast** [comment]
Hey there, 
I'm using TYPO3 V10 and php 7.4 - and need to update cs_seo, but it crashes while updating to 6.6.0. When will there be a version with PHP 7.4 support in TER @mhirdes?
THX in advance.

**Comment by mhirdes** [comment]
The current version support PHP 7.4. What crashes?
