### ISSUE TITLE
Image SEO tool with translations

### ISSUE THREAD

**Issue by samuel-lobby** [clickstorm/cs_seo#308]
Hey guys, I have a strange behaviour in the image seo tool. I have an image there with an german and english version. So I have this image two times. One for the german version and one for the english one but the images are not marked which language it is.
And if I set the alternative text for the german one (default language) I see only this image in the list which says that there is no alternative text is set.
Can I enable something in the extension that shows the difference to me?
Or is this a bug or what can I do?

Many thanks

**Comment by mhirdes** [comment]
Hey,

the modul only checks, if there is an alternative text in the default language. 

If you still have struggles may you can contact me on Slack and we take a look together.

**Comment by samuel-lobby** [comment]
@mhirdes thank's for your reply. I've wrote you on slack

**Comment by mhirdes** [comment]
A bugfix for the branch 7x is available. Please test and give me feedback.

**Comment by samuel-lobby** [comment]
Bugfix is working on your branch :-)

Many thanks to @mhirdes
