### ISSUE TITLE
503 Error: Snippetpreview & Usergroups

### ISSUE THREAD

**Issue by Ranunzel** [clickstorm/cs_seo#311]
Typo3 12.4 : If you select Access-> Usergroup in the page settings, the Snippetpreview throws an error (503 -> page settings).

![Bildschirmfoto vom 2023-06-01 13-51-51](https://github.com/clickstorm/cs_seo/assets/112628790/29f88a02-5ee4-42e7-9881-ca1c082e6caf)
![Bildschirmfoto vom 2023-06-01 13-51-51](https://github.com/clickstorm/cs_seo/assets/112628790/50158532-cca7-4d3b-9b64-a5d9a24ee0b3)
![Bildschirmfoto vom 2023-06-01 13-26-20](https://github.com/clickstorm/cs_seo/assets/112628790/ea9e9171-46bd-4671-8e61-bcb55b0945e6)

**Comment by clickstorm** [comment]
Thanks for the hint. May you can test the fix.

**Comment by mhirdes** [comment]
Fixed in version 8.1.0

**Comment by mhirdes** [comment]
Hi, hast du alle Caches geleert nach dem Update? Kannst du mich vllt. bei Slack kontaktieren und wir schauen mal zusammen drauf? VG

**Comment by websi** [comment]
@mhirdes Ich kann das Problem in der Version 8.2.1 für TYPO3 12 bestätigen. Das Problem ist das die Methode `$GLOBALS['TSFE']->determineId($GLOBALS['TYPO3_REQUEST']);` den Datensatz für die Seite wieder zurücksetzt. Dies wird nach euren Aufruf ausgeführt. Daher ist der Page Record wieder leer. https://github.com/clickstorm/cs_seo/blob/8x/Classes/Utility/TSFEUtility.php#L123

In der aktuellen 9er Version für TYPO3 13 ist scheint das behoben zu sein, aber für TYPO3 12 ist das Problem noch vorhanden.

**Comment by websi** [comment]
Quick fix:

```patch
Index: Classes/Utility/TSFEUtility.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Classes/Utility/TSFEUtility.php b/Classes/Utility/TSFEUtility.php
--- a/Classes/Utility/TSFEUtility.php
+++ b/Classes/Utility/TSFEUtility.php	(date 1728908987647)
@@ -123,6 +123,8 @@
                 $GLOBALS['TSFE']->determineId($GLOBALS['TYPO3_REQUEST']);
             }

+            $GLOBALS['TSFE']->page = $GLOBALS['TSFE']->sys_page->getPage($this->pageUid, true);
+
             // get TypoScript - see https://www.in2code.de/aktuelles/php-typoscript-im-backend-oder-command-kontext-nutzen/
             $rootlineUtil = GeneralUtility::makeInstance(RootlineUtility::class, $this->pageUid);

```
