### ISSUE TITLE
Twitter Image does not gets resolved

### ISSUE THREAD

**Issue by develth** [clickstorm/cs_seo#316]
Hi,

when saving on 8.1.0 an Image on Twitter Social section within a `news` Item, it gets persisted in DB via `sys_file_reference` on fieldname `tw_image`.
The `MetaTagGeneratorHook` otherwise is seraching for `tx_csseo_`. (Line 119).

I migrated from v10, so currently only old Fields get shown in Frontend, but not in Backend, seems like caused by this mixture. 
Would be nice, if we could keep `tx_csseo_tw_image` so we do not need to migrate.

Thanks!

**Comment by develth** [comment]
This happens also on another upgraded instance with a new cs_seo entity. Searching for `tx_csseo_og_image` but in `sys_file_reference` the `og_image` is given

**Comment by mhirdes** [comment]
Hey, sry for the late response. A fix is online incl. an Update Wizard. Can you check if this works for you and give me feedback?

**Comment by develth** [comment]
Seems it fixed it.
