### ISSUE TITLE
Fatal Page Properties Error

### ISSUE THREAD

**Issue by Ranunzel** [clickstorm/cs_seo#317]
There is again a problem with the preview, you can´t access/edit the page properties when  Page properties > Access > Publish Date is set to a Date in the Future.

**Comment by Ranunzel** [comment]
@clickstorm  oh sorry!

Typo3: 12.4.5
cs_seo: 8.1.0
error: 503

**Comment by mhirdes** [comment]
Hi, sry for the late response. You can always contact me on Slack in urgent cases. I can't reproduce this error. May we can take a look together on you TYPO3?

**Comment by mhirdes** [comment]
@Schweriner also with the dev-main branch?

**Comment by Schweriner** [comment]
@mhirdes sorry cannot reproduce or test it anymore because I'm longer inside the projekt where the problem appeared. But with the latest TER version it should be easy to reproduce it yourself by just turning on a start- and/or endtime for a page.
