### ISSUE TITLE
docs(installation): Screenshot is missing

### ISSUE THREAD

**Issue by dahaupt** [clickstorm/cs_seo#32]
https://docs.typo3.org/typo3cms/extensions/cs_seo/Administrator/Installation/Index.html

> 2. Include the TypoScript from the extension! This is shown in the screenshot below. Include optionally "Sitemap.xml for news" if you use tx_news.

**Comment by mhirdes** [comment]
Hey, thanks for your hint. I will try to fix this. Until then here is a german explanation https://www.clickstorm.de/blog/sitemap-xml-robots-txt-typo3-cs_seo/ There is also a screenshot included .

**Comment by mhirdes** [comment]
The screenshots are now shown in the extension manual.
