### ISSUE TITLE
Meta robots should be by default at index,follow

### ISSUE THREAD

**Issue by lucmuller** [clickstorm/cs_seo#320]
If a records which has no_index=0 or no_follow = 0 is displayed on a page which has no_index = 1 or no_follow = 1 then the meta robots it's not overriden.

This occurs because in file Classes\Hook\MetaTagGeneratorHook.php
the generator is only set if the value of the record is no_index or no_follow.

I will provide a merge request to correct this.

**Comment by mhirdes** [comment]
Hey, I got a little panic by the description of your ticket. But on our pages we allways set the detail page to noindex in the page settings. So this page is not indexed and not listed in the sitemap.xml. But when this page has a record as parameter there is no noindex on the page. This pages should be indexed.

To set index,follow is not necessary. This is the default.

How do you set the noindex? Also in the page settings?

**Comment by lucmuller** [comment]
@mhirdes yes, I've tried to setup the index/no_index on the page to exclude the page without details parameter from the sitemap.
But settings this results in having a no_index by default on our records who have the cs_seo IRRE for SEO options.

Did we set up something wrong in our installation ?

Here's how it goes for our installation.
Page : 
![image](https://github.com/clickstorm/cs_seo/assets/1927963/4803a82d-8371-4b37-95a9-c8a543c8fa73)
Record :
![image](https://github.com/clickstorm/cs_seo/assets/1927963/6b27f61f-36c5-4220-a8ae-0705cd8349fa)
And in the frontend
on the page with the detail of our record :
![image](https://github.com/clickstorm/cs_seo/assets/1927963/00e8d3af-fa47-4060-91d0-ed2e94121f01)

**Comment by lucmuller** [comment]
Removing the condition on the lines above would also do the trick as the $noIndex $noFollow are setup with the record value :
```
$generators['robots'] = ['value' => implode(',', [$noIndex, $noFollow])];
```
Thus resulting in having the generator always setup with the record values.

**Comment by lucmuller** [comment]
TYPO3 : 12.4.6
cs_seo : 8.1.0

**Comment by lucmuller** [comment]
Can we maybe take a look together on your TYPO3?
=> Nope, that won't make it ^^
If you consider that it should work out of the box, then something might be wrong on our side.
We'll check, as I did'nt notice anything in the first place.

I'll come back to you !

**Comment by lucmuller** [comment]
Here's my typoscript setup for meta robots generation.
```
page.meta.robots.cObject = COA
page.meta.robots.cObject {
	10 = TEXT
	10 {
		value = index
		override = noindex
		override.if.isTrue.field = no_index
	}
	20 = TEXT
	20 {
		value = ,follow
		override = ,nofollow
		override.if.isTrue.field = php_tree_stop
	}
}
```
If I remove it from my site config, then the meta robots is not rendered at all.

Do you use another kind of configuration to have a better handling of the overriding of the meta ?

Shouldn't this config be setup in cs_seo typoscript ?
I do not find any configuration for page.meta.robots in your cs_seo typoscript config (nor for description or other common meta)

Should we add some configuration in the CsSeo Yaml configuration file for a correct handling of the meta robots ? I guess no. currently we only avec yaml config for our records to overrides and no meta robots specific configuration.

**Comment by lucmuller** [comment]
Ok, so there's someting I get wrong about TYPO3 and metadata in it's latest version.

As far as I know, typoscript config must be set in order to produce metadata : https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Setup/Page/Index.html#meta

> value is the content of the meta tag. If the value is empty (after trimming), the meta tag is not generated.
> [...]
> the meta tag generated by the plugin will be used. If there is none yet, the one from TypoScript is set.

What I understand is the following :

Cs-seo do not place any content for meta robots if robots AND follow are at 0 in the record.
Then fallback to typoscript config which use, in my case the values of the page.

Would you mind giving me the triggering configuration which should generate metadata without typoscript config ?
Or maybe would you give me the typoscript config you're using for robots metatag ?

**Comment by mhirdes** [comment]
You don't need extra TypoScript. The core SEO extension handles the output for pages, the cs_seo for detail pages.

https://github.com/TYPO3-CMS/seo/blob/main/Classes/MetaTag/MetaTagGenerator.php#L119

**Comment by lucmuller** [comment]
Ok ! I've got the point.
My problem is that i us an override that is no longer useful.

> override = noindex
> override.if.isTrue.field = no_index

Thanks a lot.
