### ISSUE TITLE
PHP Warning ModifyPageLayoutContentEventListener.php line 142

### ISSUE THREAD

**Issue by opi99** [clickstorm/cs_seo#322]
If you select the Root Page in the PageTree (pid = 0), the pageInfo couldn't be loaded. Which leads to following error:

`PHP Warning: Undefined array key "doktype" in /var/www/html/typo3conf/ext/cs_seo/Classes/EventListener/ModifyPageLayoutContentEventListener.php line 142`

**Comment by opi99** [comment]
The pageInfo is the object which is tried to be loaded. That's nothing which you open.

Anyway, I see, the core do not call (anymore) the event on pid = 0, so this do not happen there, will adapt this in TV+ then (but IMHO should be fixed here).

**Comment by opi99** [comment]
Yes, this should be enough

**Comment by mhirdes** [comment]
A fix is available. Does it work for you?

**Comment by opi99** [comment]
Yes, thanks
