### ISSUE TITLE
No opening of additional file storages possible

### ISSUE THREAD

**Issue by Hobokens** [clickstorm/cs_seo#323]
I have a fresh TYPO3 12.4.8 installation with only `cs_seo` installed as local extension. 

I have created two additional `file storages`. With `filelist` I can see and edit the files in the storages. With `cs_seo`, however, I get a 503 error message 

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1343589451: Could not fetch page data for uid 2. | TYPO3\CMS\Core\Exception\Page\PageNotFoundException thrown in file /www/htdocs/w01dd3f1/dev.my-domaiin.de/typo3_src-12.4.8/typo3/sysext/core/Classes/Utility/RootlineUtility.php in line 207. Requested URL: https://dev.my-domain.de/typo3/module/file/cs-seo?token=--AnonymizedToken--&id=2%3A%2F
`

The `fileadmin folder`, which is automatically created when TYPO3 is installed, can be opened and edited by `cs_seo`.

**Comment by mhirdes** [comment]
Is the file storage public available?

**Comment by Hobokens** [comment]
Yes, the storage is public available, writable and browsable.

IF you interested I can give you access to the installation.

**Comment by mhirdes** [comment]
Sure, you can contact me on slack if you want. Or send me a mail.

**Comment by cbaur** [comment]
Has there been any solutions for this issue yet? We've got the same behavior on a TYPO3 12.4.11 installation (which was previously upgraded from 10.4), but in our case it also happens with `fileadmin/`

**Comment by mhirdes** [comment]
Not really. If you still have this problem, you can contact me on slack
