### ISSUE TITLE
Bug in setting "forceMinDescription"

### ISSUE THREAD

**Issue by SventB** [clickstorm/cs_seo#324]
Setting "forceMinDescription" is defined as "boolean" but value "140" is default value:

https://github.com/clickstorm/cs_seo/blob/main/ext_conf_template.txt#L32

This has the effect, that "forceMinDescription" is shown as inactive in "Extension Configuration", but when editing field "description" in page properties, you have to write at least 140 characters.

Btw: min 140 and max 156 characters seems to be not ideal, it's hard to find a sentence matching these values.

**Comment by mhirdes** [comment]
Thanks for the hint. It's fixed. 

Here the length should be between 150 and 160 characters. https://seopressor.com/blog/google-title-meta-descriptions-length/ And i guess there are many opinions out there, thats why I wanted to make this editable. 

What default setting would you prefere?

**Comment by SventB** [comment]
@mhirdes 
> It's fixed

Thank you

> Here the length should be between 150 and 160 characters. https://seopressor.com/blog/google-title-meta-descriptions-length/

Ok for me. But this is more an suggestion and not a must-have (but with "forceMinDescription=1", it's exactly that). 

So in my view, configuration option "forceMinDescription" makes no sense. It's very hard to find a description with this length for every page and just bothers editors and developers - and there are sooooo many reasons a page doesn't need a description at all.

**Comment by SventB** [comment]
Of course, I'm disabling this.

If you think, this setting can be useful, don't touch it. But I doubt anyone wants the description to be mandatory AND has a required length ;)

BTW, you commit was wrong, "forceMinDescription" needs to be boolean according to TCA in pages.php

**Comment by mhirdes** [comment]
With this setting the description is not Mandatory. 

Thanks again, now it should be fine.
