### ISSUE TITLE
Missing og: Fallbacks

### ISSUE THREAD

**Issue by SicorDev** [clickstorm/cs_seo#326]
Hello there,

In the latest version I found it an improvement to add this typoscript:

page.meta {
  og:title.data = page:title
  og:title.attribute = property
  og:description.data = page:description
  og:description.attribute = property
}

So if the lazy editor doesn't fill in anything on the Social Media tab it still generates a proper Card on Twitter.

BTW: og:title fallback should probably be og_title > seo_title > title

Greetings,
Manuel

**Comment by mhirdes** [comment]
Hi Manuel, it is not necessary to add them. If not set, the title tag and the meta description is used.
