### ISSUE TITLE
caching problem  while evaluation?

### ISSUE THREAD

**Issue by kiwi2101** [clickstorm/cs_seo#331]
Hello everyone,

I have a problem with the evaluation. When I evaluate a page in the backend and fix the shown problems, the evaluation tool does not update and continues to show the former errors. I have localized the error to such an extent that the call in Clickstorm\CsSeo\Service\FrontendPageService lines 113 - 120 does not return any changes. If I adjust it 

`$response = GeneralUtility::makeInstance(RequestFactory::class)->request(
            $result['url'].'?no_cache=1',
            'GET',
            [
                'headers' => ['X-CS-SEO' => '1'],
                'http_errors' => false,
            ]
        );
`

everything works. Can't find any configuration which causes this. Anyone experiencing the same issue?

cs_seo: 7.3.3
TYPO3: 11.5.26
bootstrap_package: 12.0.10

Thanks Anke

**Comment by mhirdes** [comment]
Hi Anke,

so you would like to have the no_cache parameter there?

**Comment by kiwi2101** [comment]
Hey,

that would be great. If it is configurable it would be even better.

**Comment by mhirdes** [comment]
But to be honest I guess there is something wrong with your page. If you like, we can take a look together on your system. You can contact me via Slack.

**Comment by kiwi2101** [comment]
Alright, thanks for your answer. If this is not a general problem, I will check the site again for configuration issues.
