### ISSUE TITLE
Server Error 500 - View Results

### ISSUE THREAD

**Issue by quadronet** [clickstorm/cs_seo#340]
I get a server error 500 when I try to refresh the display. 

TYPO3 V12.4.19 newest cs_seo

typo3/ajax/cs_seo/evaluate?token=b14b3631fe77da9d46f66ad0bc14c0ee0e4408b5“.
VM13795 jquery.js:9942 

XHR konnte nicht geladen werden: POST „/typo3/ajax/cs_seo/evaluate?token=b14b3631fe77da9d46f66ad0bc14c0ee0e4408b5“.

**Comment by mhirdes** [comment]
If this error still exists, contact me. We can take a look together if you want.
