### ISSUE TITLE
Conflict with title tag an tx_news

### ISSUE THREAD

**Issue by cleicht** [clickstorm/cs_seo#36]
tx_news, and other extensions set a own <title> tag in detail page with the News title. It seems that cs_seo overwrite this, an set it back to page title.
Is it possible to bypass this on some pages?

**Comment by mhirdes** [comment]
Hi. This is already explained in the manual. You can override the TS like it is shown [here](https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/OverrideTypoScript/Index.html). Or you extend the recors with the seo optiones with [Page TSconfig](https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/OverrideTypoScript/Index.html). 

Kind Regards,
Marc

**Comment by nannione** [comment]
Both links show an page not found error...

**Comment by bh-teufels** [comment]
having the same issue and links to manual not working anymore
