### ISSUE TITLE
Wrong RealURL integration prevent realurl_autoconf.php generation

### ISSUE THREAD

**Issue by christian-forgacs** [clickstorm/cs_seo#37]
Hello again,

the RealURL configuration integration in this extension since the last update prevents the default realurl_autoconf.php generation because RealURL check before generating the config array in `$GLOBALS` from RealURL and don't generate it when already an configuration is set:

Your code: https://github.com/clickstorm/cs_seo/blob/master/ext_localconf.php#L29
Condition in RealURL extension: https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Configuration/ConfigurationReader.php#L289

To add your own RealURL configuration use the RealURL hook in `ext_localconf.php`:

```php
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/realurl/class.tx_realurl_autoconfgen.php']['extensionConfiguration'][$_EXTKEY] = 'path_to_hook_class::Namespace/HookClassname->methodName'
```

Please fix it 😅  If I find time on this weekend I create a pull request. But when not I recommend to fix this issue asap.

Best regards :tada:

**Comment by mhirdes** [comment]
Fixed with version 1.8.5
