### ISSUE TITLE
[BUG] Call to a member function stdWrap() on string

### ISSUE THREAD

**Issue by grimmcreative** [clickstorm/cs_seo#40]
SEO Module funktioniert nicht mehr.

cs_seo 1.8.5
PHP7
TYPO3 7.6.15

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function stdWrap() on string | Error thrown in file /var/www/.../typo3conf/ext/cs_seo/Classes/Utility/TSFEUtility.php in line 129. Requested URL: https://.../typo3/index.php?M=web_CsSeoMod1&moduleToken=80da8e71cbcbd303f728a1aa3df0db333eb0a6fb&id=1&

**Comment by mhirdes** [comment]
Hi. Von welcher Version hast du das Update auf die 1.8.5 vorgenommen? Hast du den System Cache und den Cache im Install Tool geleert?

**Comment by grimmcreative** [comment]
Autsch. Die Frage kann ich grad glatt nicht mehr beantworten. Glaube jedoch von der 1.8.3

Caches und Co. in allen Varianten geleert usw.

**Comment by grimmcreative** [comment]
Noch zur Info:

config {
    pageTitleFirst = 1
    pageTitleSeparator >
    pageTitleSeparator.noTrimWrap = | | |
    titleTagFunction = Clickstorm\CsSeo\UserFunc\PageTitle->render
}

plugin.tx_csseo.hreflang.enable = 0

Sollte ja korrekt sein denke ich. Hatte da nur ein Ticket gesehen wo etwas dergleichen vorkam.

**Comment by mhirdes** [comment]
Bei dem anderen Ticket war das Problem, dass auf der Root Seite generell kein TypoScript hinterlegt war. Demnach konnte das TSFE nicht initialisiert werden. Der Fehler wird in 1.8.5 abgefangen. Ich kann dir nur anbieten, mal mit einen Blick ins Backend zu werfen (per TeamViewer o.ä. oder temporären Zugang).

**Comment by grimmcreative** [comment]
Na das wäre ja mal nice ;)
TeamViewer 129 959 956

**Comment by mhirdes** [comment]
Schreibst du mir eine E-Mail, wie und wann? hirdes@clickstorm.de

**Comment by mhirdes** [comment]
Hier kam der Fehler daher, dass ebenfalls kein TypoScript auf der obersten Seite angelegt war. Der Fehler ist mit dem Commit 584cf1e3671f909dfb0bfb2a25e8a99f1f70bff1 behoben wurden.

**Comment by develth** [comment]
Hallo, 

der Fehler besteht leider noch immer. Erhalte ihn wenn ich eine Seite später von "Seite" zu "Verweis" ändere.

BG

**Comment by bh-teufels** [comment]
Habe denselben Fehler:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function stdWrap() on string | Error thrown in file /var/www/[...]/web/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php in line 3664. Requested URL: https://my-domain.de/`

Typo3 9.5.11
PHP 7.3
cs_seo 4.2.1
