### ISSUE TITLE
TYPO3 8.5.1: $.post(...).success is not a function

### ISSUE THREAD

**Issue by nebrot** [clickstorm/cs_seo#41]
The function to evaluate a page creates an error in TYPO3 8.5.1:
![jquery-ajax-bug](https://cloud.githubusercontent.com/assets/6941112/22140956/d8ac364c-deef-11e6-89d9-77ba00aa26ab.png)

TYPO3 8 uses jQuery 3 ( https://forge.typo3.org/issues/77249 ). With jQuery 3 there is no "success" anymore ( https://jquery.com/upgrade-guide/3.0/#breaking-change-special-case-deferred-methods-removed-from-jquery-ajax ), replacing it in jquery.cs_seo.evaluation.js with "done" resolves the issue. CsSeoController.js seems to be also affected.

**Comment by mhirdes** [comment]
Thanks for the hint. We will fix this

**Comment by mhirdes** [comment]
It's in all dev versions. Thanks again.
