### ISSUE TITLE
TS Override misspelling

### ISSUE THREAD

**Issue by dhuf** [clickstorm/cs_seo#43]
It seems that there is an error in the https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/OverrideTypoScript/Index.html#override-typoscript config, 

for the **page.headerData.tx_csseo** shouldn't it be **page.headerData.654** instead as in

https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/meta.ts
Best,
Daniel

**Comment by mhirdes** [comment]
Thanks Daniel for your hint. It's fixed.
