### ISSUE TITLE
[BUG] Hardcoded l10n_parent, sys_language_uid

### ISSUE THREAD

**Issue by r3h6** [clickstorm/cs_seo#47]
In HeaderData::getAllLanguagesFromItem control fields should be taken from the TCA ctrl section instead of being hardcoded.
This is a problem when extending own tables with a different field name for the l10n_parent (sys_language_uid) field.

https://docs.typo3.org/typo3cms/TCAReference/Reference/Ctrl/Index.html#languagefield
https://docs.typo3.org/typo3cms/TCAReference/Reference/Ctrl/Index.html#transorigpointerfield

**Comment by mhirdes** [comment]
Pull request was merged. Thanks again.
