### ISSUE TITLE
[BUG] TSconfig fallback not respected for google preview 

### ISSUE THREAD

**Issue by r3h6** [clickstorm/cs_seo#49]
When a fallback for a custom table is defined, the preview will not show the fallback properties.
![bugpreview](https://cloud.githubusercontent.com/assets/4550541/22504293/dfc1ece4-e875-11e6-977d-d78fcd5ecf72.jpg)

**Comment by mhirdes** [comment]
Fixed in branch 1.x. Maybe you can test it, too?
