### ISSUE TITLE
[FEATURE] Including settings for the extension "blog"

### ISSUE THREAD

**Issue by Mairex** [clickstorm/cs_seo#50]
To support the most hopeful extension for a Typo3 blog function, it would be helpful to integrate the "cs_seo" settings for the new "blog" extension from the core team (Typo3 GmbH).

**Comment by mhirdes** [comment]
Hi, thansk for your request. You can extend any records you like with cs_seo settings. https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/ExtendExistingModel/Index.html 
And you can create a sitemap for each extension you like https://docs.typo3.org/typo3cms/extensions/cs_seo/Developer/ExtendSitemap/Index.html 
Kind Regards,
Marc
