### ISSUE TITLE
add tx_csseo_no_index field in pages_language_overlay table?

### ISSUE THREAD

**Issue by davdenic** [clickstorm/cs_seo#51]
My goal is to differentiate the behaviour like:
the default page is indexable, while the translated is not. 
That could be the case when the editor is preparing a translated page and doesn't like to let google index the translated page before it's ready.
Now if the default page is indexable than the related translated page(s) are too. which is maybe true or not.
I was wondering if is possible to add tx_csseo_no_index also to the pages_language_overlay and relative scripts.
What do you think?

**Comment by mhirdes** [comment]
If the editor is preparing a page overlay he could set the page to hidden and nobody can see it. Fields like include in search are also not available in overlays. If I am right, the pages_language_overlay table will also be dropped in further TYPO3 versions. I think it is not the urgent feature. But you can contribute and make a pull request if you like.
