### ISSUE TITLE
Feature suggestion: Possibility to set x-default

### ISSUE THREAD

**Issue by janein** [clickstorm/cs_seo#52]
Hi,

wouldn't it be nice to be able to set the `x-default` for the hreflang?
I already looked into it to implement it, but sadly I'm not fit enough with typoscript to get it working.

I think it would be quite easy to implement in php, so if there is anyone who could to this in typoscript I would be more than happy.

thanks for the great extension! :+1:

**Comment by mhirdes** [comment]
Hi,

you can set the x-default already. If it is an extra language, e.g. you can set 

## language Uids
plugin.tx_csseo.hreflang.ids = 0,1,2
## language Keys 
plugin.tx_csseo.hreflang.keys = de,x-default,en

An other interpretation is that x-default is page where the user can choose his language. So the link is static. In this case you can set
page.headerData.677 = TEXT
page.headerData.677.value = <link rel="alternate" href="http://example.com/" hreflang="x-default" />

I hope this works for you. 

Kind Regards,
Marc

**Comment by janein** [comment]
Hey, thanks for the tip!
As I needed to define my default language with 2 hreflangs, I just passed its uid tw times like this:

```
## language Uids
plugin.tx_csseo.hreflang.ids = 0,0,1,2
## language Keys
plugin.tx_csseo.hreflang.keys = de,x-default,en,it
```## language Uids
plugin.tx_csseo.hreflang.ids = 0,0,1,2
## language Keys
plugin.tx_csseo.hreflang.keys = de,x-default,en,it

works like a charm :)
