### ISSUE TITLE
[FEATURE] Make the evaluation configurable by access right instead of em conf

### ISSUE THREAD

**Issue by fjacobi** [clickstorm/cs_seo#53]
Would love to enable/disable the evaluation module by editor/editor group.

We had mixed feedback regarding the module itself and some editors felt overwhelmed by it.

**Comment by fjacobi** [comment]
Works perfectly. Thanks.

**Comment by andrewpricesrs** [comment]
Hi I am having problems getting this to work still after adding `mod.web_layout.tx_csseo.disable = 0` in page TSconfig. Any ideas ? https://stackoverflow.com/questions/58639999/typo3-modifying-tsconfig-for-1-page-doesnt-work-for-cs-seo Thanks

**Comment by Ugluuglu** [comment]
Hello, 
`page.mod.web_layout.tx_csseo.disable = 0`
`mod.web_layout.tx_csseo.disable = 0`

are both not working in my backend. The evaluator keeps being visible. I use TYPO3 10.4.28 and CS_SEO 6.5.0
