### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by farconada** [clickstorm/cs_seo#55]
Would you mind to ask to the TYPO3 team to add this extension to translation server. I want to translate it to spanish.
https://forge.typo3.org/issues/80136
I did it already but I think that the request should come from the owner

Thanks

**Comment by mhirdes** [comment]
Hi, thanks for your support. I asked the team, too. https://forge.typo3.org/issues/80136

**Comment by farconada** [comment]
Translated

**Comment by mhirdes** [comment]
Great. Thanks a lot.
