### ISSUE TITLE
tx_csseo_tw_image doesn't exist in pages_language_overlay

### ISSUE THREAD

**Issue by jacrasmussen** [clickstorm/cs_seo#56]
I get database errors in TYPO3 8.6.1 while having the field in override file and upon removing the field, the error disappears.

As the field doesn't exist in ext_tables.sql for the overlay table, and either it must be removed from the TCA override or be added to the ext_tables.sql in order to avoid errors.

**Comment by mhirdes** [comment]
Hi,

thanks for the hint. I added the fields to the db. I had to add the TCA override handling, so that the images will also be shown in the translated pages. So I added the fields now to ext_tables.sql to avoid the db error.
