### ISSUE TITLE
News should be og:type article

### ISSUE THREAD

**Issue by jwittorf** [clickstorm/cs_seo#57]
First off: thank you very much for this extension :) I'm almost done with my implementation, just one last thing is missing.

I wanted to overwrite the `og:type` for news entries with TS like this:

```
[globalVar = GP:tx_news_pi1|news > 0]
	page.headerData.654.30.5.value = <meta property="og:type" content="article" />
[global]
```

But it doesn't change the news. When I remove the condition and only set `page.headerData.654.30.5.value = <meta property="og:type" content="article" />` all pages are using `article`, but the news still use `website`.

I found `$content .= $this->printMetaTag('og:type', 'website', 1);` in line 323 of `UserFunc/HelperData.php` and the corresponding TS:

```
[userFunc = Clickstorm\CsSeo\UserFunc\HeaderData::checkSeoGP()]
	config.noPageTitle = 2
	page.headerData.654 = USER
	page.headerData.654.userFunc = Clickstorm\CsSeo\UserFunc\HeaderData->getMetaTags
[else]
	(...)
	# stuff like 
	page.headerData.654.30.5.value = <meta property="og:type" content="website" />
```

So because of the GP of news it won't go to the `else` block and use TS for rendering. Instead if uses PHP which I can't influence. Would it be possible to adjust the extension a bit so we can have `<meta property="og:type" content="article" />` for news?

**Comment by mhirdes** [comment]
Hi,

Now you can configure
```
[globalVar = GP:tx_news_pi1|news > 0]
	plugin.tx_csseo.social.openGraph.type = article
[global]
```

Does that work for you?

**Comment by jwittorf** [comment]
Hi,

thanks for the quick response, I've just tested the latest dev-master.

That resulted in removing the "SEO" tab in the news, I think that shouldn't happen on purpose.

Additionally adding the typoscript as described by you didn't have any effect. Could you please re-check, especially the "lost" tab?

Thanks in advance!

**Comment by mhirdes** [comment]
Everything testet. It works fine in 2.0. If you got any other error, please add a new issue. Thanks.
