### ISSUE TITLE
[BUG] Incompatible extension found!

### ISSUE THREAD

**Issue by grimmcreative** [clickstorm/cs_seo#6]
TYPO3 7.6.9 
Incompatible extension found!
The following extensions are not compatible. Please uninstall them and try again. 
Uninstall cs_seo

cs_seo Version: 1.4.1

**Comment by clickstorm** [comment]
Thanks for you advice. In the install tool check the db is not initialized so this throws an error. But the extension works. Now I ask in the dev version if the db is initialized. Maybe you try the dev version.  There will be no error shown.
