### ISSUE TITLE
Creating Sitemap with records of language [All] (-1) throws realurl error (2.1.9)

### ISSUE THREAD

**Issue by hilgm** [clickstorm/cs_seo#61]
If records on a sitemap contain records where the language ist set to [ALL]  the following error is thrown and no sitemap is created:
<pre>
#1482160086: RealURL could not process "/index.php?id=31&tx_my_ext[obj]=571&L=-1" because "L" parameter is invalid. More information can be found in the web server error log. 
</pre>

This is the case for realurl 2.1.9 and seem to be based on a change in reaurl handling unknown L parameters.

Maybe it can be fixed by changing the handling of L parameter <1 in  Clickstorm\csSeo\UserFunc\Sitemap (Line 132)

thx & br
Michi

**Comment by mhirdes** [comment]
Thanks for the hint. A bugfix is included in the dev version.
