### ISSUE TITLE
Extended model error on save in 8.6 for v1

### ISSUE THREAD

**Issue by r3h6** [clickstorm/cs_seo#63]
Error Message: Argument 3 passed to TYPO3\CMS\Core\DataHandling\Localization\DataMapProcessor::synchronizeTranslationItem() must be of the type integer, null given, called in /var/www/vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/Localization/DataMapProcessor.php on line 195

Reproduce:
1) Extend a custom table (TSconfig) for seo.
2) Add seo inline record and save

The problem is probably some wrong TCA configuration.

**Comment by mhirdes** [comment]
Hi. Which Version  of cs_seo, TYPO3 do you use?

**Comment by r3h6** [comment]
cs_seo 1.8
TYPO3: 8.61

I fixed it locally, push request follows

**Comment by mhirdes** [comment]
I commited this also for the master. Thanks again.
