### ISSUE TITLE
Conflict with nc_staticfilecache

### ISSUE THREAD

**Issue by jwittorf** [clickstorm/cs_seo#66]
I am experiencing a conflict with [nc_staticfilecache](https://typo3.org/extensions/repository/view/nc_staticfilecache) 3.6.0 installed (realurl disabled, just to make sure).

When logged into the backend everything seems fine. The `[userFunc = Clickstorm\CsSeo\UserFunc\HeaderData::checkSeoGP()]` returns the news table and then goes to `page.headerData.654.userFunc = Clickstorm\CsSeo\UserFunc\HeaderData->getMetaTags`.

But when not logged in the `[userFunc = Clickstorm\CsSeo\UserFunc\HeaderData::checkSeoGP()]` doesn't return the news table and then goes to `config.titleTagFunction = Clickstorm\CsSeo\UserFunc\PageTitle->render`. There the `$page` doesn't have a `'tx_csseo_title` and therefore uses the regular `'title'` e.g. "Details".

P.S.: Using TYPO3 7.6.16

**Comment by mhirdes** [comment]
Hi. Do you use fluidpages?

**Comment by jwittorf** [comment]
Yes sir, 3.5.0 to be exact.

**Comment by mhirdes** [comment]
Then this is the reason. I had also a TYPO3 with fluidpages. After deinstalling the extension and use backend layout evyrthing works fine. I think the fluidpages caches the headerdata.

**Comment by jwittorf** [comment]
Got it fixed, fluidpages seemed not to be the problem. Moved the pageTSConfig.ts and extTSConfig.ts with the `tx_csseo.1 = tx_news_domain_model_news` from ext_tables.php to ext_localconf.php in my provider extesion.
