### ISSUE TITLE
Google Analytics Download Tracking JavaScript is included although no GA ID is set

### ISSUE THREAD

**Issue by jwittorf** [clickstorm/cs_seo#67]
The `EXT:cs_seo/Resources/Public/JavaScript/jquery.cs_seo.ga.js` in https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/tracking.ts line 63 is included although there is no Google Analytics ID defined. It should only be included if there is an ID. It's because the following code checks for an non-existing object.

```
- 654.if.isTrue < plugin.tx_csseo.googleAnalytics
+ 654.if.isTrue < plugin.tx_csseo.tracking.googleAnalytics
```

The `plugin.tx_csseo.googleAnalytics` doesn't exist, there should be a `tracking` added so it results in `plugin.tx_csseo.tracking.googleAnalytics` which actually exists.

This is no major issue, I'd just wanted to report it. The TypoScript-Object-Browser is a bit mixed up, too:
![grafik](https://cloud.githubusercontent.com/assets/2085721/24652495/709a01c4-1932-11e7-879f-4cfb660fc6e9.png)

It should look like this:
![grafik](https://cloud.githubusercontent.com/assets/2085721/24652516/813baa32-1932-11e7-80f6-303a2846cdfa.png)

P.S.: Just a minor suggestion for the `gaOptout()`, how about giving the user some feedback after clicking the link and adding something like `alert("Google Analytics was temporarily disabled.");` to the end of the function?

**Comment by mhirdes** [comment]
Hi. Thank you very much. I fixed this in the dev. The PS section I don't really understand. Maybe you can add a new issue or create a pull request. Kind Regards, Marc
