### ISSUE TITLE
TYPO3 8.7 UpdateScript: Call to undefined method TYPO3\CMS\Core\Messaging\FlashMessage::render()

### ISSUE THREAD

**Issue by nebrot** [clickstorm/cs_seo#68]
UpdateScript (/ext/cs_seo/class.ext_update.php) in extensionmanager throws a fatal error because of removed method render() (see "[Breaking: #72438 - Remove deprecated code from FlashMessage](https://docs.typo3.org/typo3cms/extensions/core/8-dev/Changelog/8.0/Breaking-72438-RemoveDeprecatedCodeFromFlashMessage.html)"):

![cs_seo-1](https://cloud.githubusercontent.com/assets/6941112/24711935/b2c69c0c-1a21-11e7-979f-2bb90109777e.png)

![cs_seo-2](https://cloud.githubusercontent.com/assets/6941112/24711944/b8c89fc4-1a21-11e7-8852-57508656d731.png)

cs_seo: 2.0.0
TYPO3: 8.7.0
PHP: 7.0.15

**Comment by mhirdes** [comment]
Thanks for the hint. Is fixed in current dev.
