### ISSUE TITLE
Additional TCA definition depends on extension load order

### ISSUE THREAD

**Issue by HenningCash** [clickstorm/cs_seo#69]
(Sorry for the confusing explanation - the issue is hard to describe)

The definition of additional `tx_csseo` columns for foreign tables currently works via `TCA/Overrides`. This requires the "to-be-overriden" extensions to be loaded before `cs_seo`, but because the TYPO3 extension loading order relies on the dependency graph it's very difficult if not impossible to ensure `cs_seo` to be loaded before these other extensions. If cs_seo is loaded too early the column definition will be dropped entirely and the "SEO" tab gets lost.

E.g. you have a provider extension `my_template` which has `cs_seo` and `news` as dependency, the loading order of `cs_seo` and `news` is undefined because neither of them requires each other as dependency. Even the dependency order in `my_template` is irrelevant because independent extensions are sorted alphabetically.

What I'm trying to say is the additional TCA definition [from here](https://github.com/clickstorm/cs_seo/blob/master/Configuration/TCA/Overrides/tx_csseo_domain_model_meta.php) should be done in another place. Maybe via Hook/Signal but I couldn't find a fitting one.

**Comment by mhirdes** [comment]
Hey. Thanks for the hint. We now use a hook. Maybe you can test the 2.0.1-dev and give us feedback.
