### ISSUE TITLE
[BUG] incompatible with FluidTYPO3.org Extensions

### ISSUE THREAD

**Issue by grimmcreative** [clickstorm/cs_seo#7]
Hello, 
when using cs_seo together with FluidTYPO3 Extension e.g. vhs, flux, fluidcontent, fluidpages
the site root page wont show any created FCEs (Fluidcontent Elements).
All other Subpages are not affected - only rootsite.

**Comment by mhirdes** [comment]
Thanks again. Fixed with last commit. Maybe you can test it.
