### ISSUE TITLE
Wrong breadcrumb for Mounting-Point pages

### ISSUE THREAD

**Issue by mat-hew1** [clickstorm/cs_seo#71]
For mounting-point pages is breadcrumb for the destination page generated instead of the reference-page. This is not correct and causes false records in real-url cache if the destination page is not in the same root.
Example: page 1-12-123 mount the page 2-23-234. Breadcrumb should be 1-12, currently is 2-23.

**Comment by mat-hew1** [comment]
Solution suggestion:
`--- a/Classes/UserFunc/StructuredData.php
+++ b/Classes/UserFunc/StructuredData.php
@@ -106,7 +106,13 @@ class StructuredData
     {
         /** @var  \TYPO3\CMS\Frontend\Page\PageRepository $pageRepository */
         $pageRepository = GeneralUtility::makeInstance(PageRepository::class);
-        $rootline = $pageRepository->getRootLine($GLOBALS['TSFE']->id);
+        /** @var \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController[] $GLOBALS */
+        $id = $GLOBALS['TSFE']->id;
+        if (!empty($GLOBALS['TSFE']->MP)) {
+            // mouting point page - generate breadcrumb for the mounting point reference page instead
+            list(,$id) = explode('-', $GLOBALS['TSFE']->MP);
+        }
+        $rootline = $pageRepository->getRootLine($id);

         $cObject = GeneralUtility::makeInstance(ContentObjectRenderer::class);
`

**Comment by mhirdes** [comment]
Hi. Thanks for the hint. Could you create a pull request?

**Comment by mhirdes** [comment]
Thanks for this fast response. I'll close this ticket.
