### ISSUE TITLE
Could not determine the child object type.

### ISSUE THREAD

**Issue by tomhatzer** [clickstorm/cs_seo#73]
Hi everybody!

Thank you very much for this nice extension!
We've upgraded to the latest Version of cs_seo and now receive the following error when running the Extbase-CommandController-Task:

```
Execution of task "Extbase-CommandController-Task (extbase)" failed with the following message: Could not determine the child object type.

PHP Warning
Core: Error handler (BE): PHP Warning: class_parents(): object or string expected in /var/www/typo3_src/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php line 283

PHP Warning
Core: Error handler (BE): PHP Warning: in_array() expects parameter 2 to be array, boolean given in /var/www/typo3_src/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php line 283
```

Running the scheduler task fails everytime as it results in the error above.

System information:
> TYPO3 CMS 7.6.15
> Operating system: Linux
> PHP version: 7.0.7
> PHP CGI detected: No

Do you possibly know what could have caused the error and how to fix it?

Thank you very much and best wishes
Tom

**Comment by mhirdes** [comment]
Hi Tom,

I checked it again in my TYPO3. Everything works fine. If you start the task manually in the backend, does this error occurs, too? Does you CLI also use PHP 7? What are your task settings?

Kind Regards,
Marc

**Comment by mhirdes** [comment]
Hey. Because there are no new information I will close this issue. If you got new ones reopen it.

**Comment by tomhatzer** [comment]
Just a quick update on this one (sorry for the late reply). It looks like it was a cache issue. Cleaned the cache (had to remove the typo3temp directory) and it worked again.

Thanks for your help!
