### ISSUE TITLE
Evaluation in page module only shows results for default language

### ISSUE THREAD

**Issue by Hafax** [clickstorm/cs_seo#75]
Within a single-tree, multilanguage installation, the evaluation score and hints are only shown for the default language. Using the **Update** button in other languages within the page module, results in an update but no score and hints are shown within the page module.

In the **SEO** module however, the score is listed for other languages when switching to the **Results** view.

Tested with 
TYPO3 6.2.30 -> cs_seo 1.8.6
TYPO3 7.6.16 -> cs_seo 2.0.0

Is this a configuration problem or is this feature not available for other languages then the default language?

Thank you for the great extension, would be really helpfull to be able to use the evaluation feature for other languages as well.

**Comment by mhirdes** [comment]
![13-04-_2017_12-11-25](https://cloud.githubusercontent.com/assets/915162/25000634/6015c7c2-2042-11e7-9f48-e2ed4a07f74e.png)

Hey, I checked it again and it works as it should. The feature is available for all languages.

Please check your setup. Is the page translated? Did you set a domain record? I can offer you to look together via TeamViewer or you provide me a temporary access.

**Comment by Hafax** [comment]
Thank you for the quick respond. 

I just setup a fresh TYPO3 6.2.30, configured 2 languages, set a domain record and translated the page. The update button in the translation doesn't bring up andy results for the translated page in my case. 

Can't find out what I am missing. I can provide you temporary access to the test installation if you want to have a look.

**Comment by mhirdes** [comment]
is the language param L? so is the page avilable by L=1? you can send me a mail marc_hirdes@gmx.de

**Comment by Hafax** [comment]
Yes, the language param is L and the page is available by adding L=1 to the URL. I sent you an email.

**Comment by mhirdes** [comment]
Fixed for branch 1.x with 324fbb4e577a215efc5c5decaf2eff9b12c44822 
Works in 2.0.1 as it should.
