### ISSUE TITLE
Sysfolder ignored in sitemap

### ISSUE THREAD

**Issue by mindbreaker** [clickstorm/cs_seo#77]
If I've pages in the sysfolder, the pages will be excluded in the sitemap. If I choose a shortcut instead as superordinate folder, the pages will appear in the sitemap. Is there a reason for excluding sysfolders?

**Comment by mhirdes** [comment]
Hey. Which Version of cs_seo do u use. This should work in the current version. I tested it again and it works as it should.

**Comment by thasmo** [comment]
I'm using `2.0.1` but subpages of sys-folders are not shown in the sitemap. In addition any custom doktypes configured in `evaluation.evaluationDoktypes` are also not listed in the sitemap.

**Comment by maniobi** [comment]
https://github.com/clickstorm/cs_seo/issues/82

**Comment by mhirdes** [comment]
Hey. The TYPO3 Version was the missing hint. Bugfix is available in dev-master. Can you please give me feedback if it now works for you? Thanks in advance.

**Comment by mhirdes** [comment]
If you need another doktype in the sitemap, then overwrite typo3conf/ext/cs_seo/Resources/Private/Partials/Sitemap/Page.xml

**Comment by thasmo** [comment]
@mhirdes Is there a simple way to overwrite this single file only? May I suggest to make the valid doktypes configurable and use the new configuration option within the template's if statement?

**Comment by thasmo** [comment]
Currently it's impossible to override the template via configuration because of [this](https://github.com/clickstorm/cs_seo/blob/master/Classes/UserFunc/Sitemap.php#L80). It's only possible to replace the whole [userfunc](https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/PageTypes/sitemap-655.ts#L31) which is not optimal.
