### ISSUE TITLE
noindex,follow as default

### ISSUE THREAD

**Issue by mindbreaker** [clickstorm/cs_seo#79]
If you mark a page as "noindex", cs_seo will generate the meta tag:

`<meta name="robots" content="noindex,nofollow" />`

But the **nofollow** entry is not  recommended for internal links [ (Source: Google)](https://searchenginewatch.com/sew/news/2298312/matt-cutts-you-dont-have-to-nofollow-internal-links).

Default meta robots tag should be:

`<meta name="robots" content="noindex,follow" />`

**Comment by mhirdes** [comment]
Thanks for the hint. Is changed in the current dev.
