### ISSUE TITLE
anonymizeIp for Analytics as option

### ISSUE THREAD

**Issue by Chriz74** [clickstorm/cs_seo#80]
It would be great to set the anonymizeIp-Function 
`ga('set', 'anonymizeIp', true);`
as an option in constants or setup for Google Analytics. 
Here in Germany this is a musthave ;)

**Comment by mhirdes** [comment]
Hey. Currently this is set by default as you can see in typo3conf/ext/cs_seo/Configuration/TypoScript/Setup/tracking.ts. 
If somebody would like to override this code, he could change the TypoScript page.jsInline.654.10.wrap. Is this an option for you?

**Comment by Chriz74** [comment]
ah. i did not see that! Then forget it.... my bad ;) works like a charm!
