### ISSUE TITLE
TYPO3 8.7 - "Execute database migrations on single rows" fails

### ISSUE THREAD

**Issue by derhansen** [clickstorm/cs_seo#81]
When updating a TYPO3 7.6 Website to TYPO3 8.7, the task "Execute database migrations on single rows" in the install tool fails with an exception, because the fields "tx_csseo_og_image" and "tx_csseo_tw_image" are not present for the table "pages_language_overlay".

```
An exception occurred while executing 'SELECT `uid`, `tx_csseo_og_image`, `tx_csseo_tw_image`, `pid` FROM `pages_language_overlay` WHERE (`uid` = ?) AND (`pages_language_overlay`.`deleted` = 0)' with params [1]: Unknown column 'tx_csseo_og_image' in 'field list'
```

I removed both fields in the `pages_language_overlay.php` file and then the task executed successfully. After that, I was not able to reproduce the problem again.

**Comment by mhirdes** [comment]
Hey, if you update cs_seo to the current version 2.0.1 and check the database analyze this field will be added to the database. After that you can update to TYPO3 8.7. Kind regards.
