### ISSUE TITLE
Database error for non-existent l10n fields on single-language project

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#87]
When working on a single-language TYPO3 installation and when configuring a custom table to have SEO fields, there's an error in the frontend if certain fields like `l10n` do not exist on the table.

```
Unknown column 'l10n_parent' in 'where clause'' (46 chars)
SELECT sys_language_uid FROM tx_movies_movie WHERE (l10n_parent = 1014 OR uid = 1014) AND (`tx_movies_movie`.`deleted` = 0) AND (`tx_movies_movie`.`hidden` = 0)' (160 chars)
```

Can this queries be made optional if only a single language is used or is it absolutely mandatory to create `l10n` fields even if the records won't be translated at all? I have `hreflang` disabled in the `pagetsconfig` settings but this error still comes up.

**Comment by mhirdes** [comment]
Hey,

I add the condition
```
if (!isset($GLOBALS['TCA'][$table]['ctrl']['transOrigPointerField']) || !isset($GLOBALS['TCA'][$table]['ctrl']['languageField'])) {
```
so this error should be avoid.

Kind Regards,
Marc
