### ISSUE TITLE
[FEATURE] Fall back social images

### ISSUE THREAD

**Issue by thegrbteam** [clickstorm/cs_seo#9]
Great work on this, thank you.

Feature to be able to set global Facebook og:image and Twitter card to fall back on if one isn't selected in the page.

**Comment by mhirdes** [comment]
Hey, thanks but you can already set a fallback image in TS with plugin.tx_csseo.social.defaultImage .

**Comment by thegrbteam** [comment]
Thank you, sorry I must have missed that. Can you set a different one for og:image than for twitter:card?

**Comment by mhirdes** [comment]
Is this so necessary? If so, should we also make a fallback if no extra twitter:card image is set?

**Comment by thegrbteam** [comment]
Yes as Twitter Cards and Open Graph use different pixel dimensions if you want the optimum visibility for your image.

Best regards,

Dan Evans

**Comment by mhirdes** [comment]
Yes I know. So in the editor you can set different dimensions. Bu ok, I'll add an extra option for a special Twitter image. If it is not set, the open graph image will be the fallback.

**Comment by mhirdes** [comment]
So the default image option is available. The fallback order is:

1. Twitter image is set on the reocrd
2. Open Graph image is set on the reocrd
3. Default Twitter image
4. Default Open Graph image

All images are scaled to the dimensions that are set in `plugin.tx_csseo.social.twitter.image.`

Does that work for you?

**Comment by thegrbteam** [comment]
That's excellent, thanks!
