### ISSUE TITLE
Support for fb meta-tags

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#90]
I couldn't find any information about how to render `fb:*` meta-tags with `cs_seo`, so I propose to integrate this feature.

Specifically it would be nice to configure and render those tags:
* `fb:admins`
* `fb:app_id`

**Comment by mhirdes** [comment]
Hey. I don't think that editors have to change this field, so you can easily set them via TypoScript if you needed them.

https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Meta/Index.html 

I hope this is an option for you?

**Comment by thasmo** [comment]
Indeed, thanks for your input. After thinking about it, it doesn't make so much sense to integrate it actually.
