### ISSUE TITLE
Use new file extensions

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#91]
The currently used file extension for TypoScript files in the project is `ts` and clashes with the file extension for TypeScript. In TYPO3 8.7 the file extensions have officially been changed to `typoscript` for TypoScript files and `tsconfig` for TSConfig files.

If possible, please change the file extensions to the new ones.

**Comment by nebrot** [comment]
It's not included in TYPO3 8.7.1 yet, they add it in 8.7.2 and 9.x (commit is from 17.05.2017 https://forge.typo3.org/issues/78161).

**Comment by thasmo** [comment]
I see. But changing the file extension should work on older and current TYPO3 versions also right away because file extensions are not validated/restricted.

**Comment by mhirdes** [comment]
We will wait until the new TYPO3 release is available
