### ISSUE TITLE
Fallback for og_image on models doesn't work

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#92]
I'm trying to configure a fallback-field for the `og_image` on a model like this:

```
tx_csseo {
    1 = tx_ext_model
    1 {
        enable = GP:modelid

        fallback {
            og_image = poster
        }
    }
}
```

It seems setting `og_image = poster` is the right thing to do because `tx_csseo_og_image = poster` just renders the default `og_image`, while using `og_image = poster` doesn't render the `og:image` tag at all.

Do I miss something or is this not working (yet)?

**Comment by mhirdes** [comment]
use TypoScript Setup `plugin.tx_csseo.social.defaultImage` or `plugin.tx_csseo.social.twitter.defaultImage`

you can use a TypoScript Condition here like

``
[globalVar = GP:tx_news_pi1|news > 0]
``

**Comment by thasmo** [comment]
If you don't mind, would you be so kind to provide a full example for setting the defaultImage using a field from a model? I tried this without success:
```
[globalVar = GP:movieId > 0]
    plugin.tx_csseo.social {
        defaultImage = FILES
        defaultImage {
            references {
                table = tx_ext_model
                uid.data = GP:modelId
                fieldName = poster
            }

            renderObj = TEXT
            renderObj {
                data = file:current:publicUrl
            }
        }
    }
[global]
```

**Comment by mhirdes** [comment]
ok. sry. I thought you will add a default image when no image in any field is set. This can be done via TypoScript and TypoScript Conditions.

I will check if fallback fields for images also work.

**Comment by thasmo** [comment]
It can be done but it's quite a bit of complex TypoScript to achieve a proper solution which also takes the cs_seo fields into account. It would be nice if the fallback would also handle FAL fields.

**Comment by poomer1988** [comment]
Same Problem here. Fallback for og_image and twitter_image doesn't work.

**Comment by mhirdes** [comment]
Hey. It should now work. Maybe you can test it, too. Enter in the page TSconfig
``
tx_csseo {
	# new index and table name of the model
	1 = tx_news_domain_model_news
...
	# if the model already has fields like title etc. define them as fallback
	1.fallback {
...
		# cs_seo description field fallback = news description field
		og_image = fal_media
	}
}
``

Kind Regards,
Marc

**Comment by thasmo** [comment]
@mhirdes It **only** works if the cs_seo IRRE-record exists. When there's no record created, an error occurs:
```
#1316789798: UID of related record has to be an integer. UID given: "" (More information)
InvalidArgumentException thrown in file
/vagrant/vendor/typo3/cms/typo3/sysext/core/Classes/Resource/FileRepository.php in line 75.

16 TYPO3\CMS\Core\Resource\FileRepository::findByRelation("tx_movies_movie", "poster", NULL)
15 Clickstorm\CsSeo\Utility\DatabaseUtility::getImagePath("tx_movies_movie", "poster", NULL)
```
`meta['uid']` seems to be missing.

**Comment by thasmo** [comment]
There's another issue where the `og_image` of the IRRE-record is used even if the IRRE-record is disabled (hidden).
