### ISSUE TITLE
Support all OpenGraph object types

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#93]
It would be nice to choose the actual OpenGraph object type via select-field on the page/record and choose from the [officially defined ones](http://ogp.me/#types). When changing the type on the select-field, only relevant fields should be displayed. For example when changing the type to `music.radio_station`, only the field `music:creator` should be displayed (besides the general fields). In addition the new fields should also be supported by all other available extension features like setting fallback fields for models etc.

Is there currently a way to change the `og_type` for a model or for pages via TypoScript?

**Comment by mhirdes** [comment]
Hey. In my opionion editors don't use this. Yes you can overwrite the type via TypoScript

`plugin.tx_csseo.social.openGraph.type` I need to add this to the doc.

To set this via TypoScript is enough. So you can change the type for news or events. But I really don't want to have too much fields in the page settings.
