### ISSUE TITLE
Set Title only as default

### ISSUE THREAD

**Issue by Shentao83** [clickstorm/cs_seo#95]
Hi there, 

- I want to integrate clickstorm seo to a big website
- There are many pages, and each one of them has the " | " added at the end 
- I have not found a way to turn that behaviour off globally (or having "Title only" checked as default)

**Comment by mhirdes** [comment]
Hey. Explained is this here https://docs.typo3.org/typo3cms/extensions/cs_seo/Configuration/Index.html if you dont use a prefix or suffix just use `config.pageTitleSperator >`. This setting is described in the official TypoScript refernce  https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#pagetitleseparator I hope this helps you and solves your problem. Kind regards, Marc

**Comment by Shentao83** [comment]
Oh my god, I can't believe I could overlook this! I am really sorry to bother you! Thank you for your awesome extension!
