### ISSUE TITLE
Mounted pages do not show up in the `sitemap.xml`

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#96]
It seems that mounted pages and it's sub-pages don't get included in the `sitemap.xml` output. This is especially problematic if the mounted pages are not publicly accessible directly but only via a mount point.

Is there a way to achieve this? It would be a useful addition to the extension if it can render mounted pages (and mount points) in the `sitemap.xml`.

**Comment by mhirdes** [comment]
Hey. Maybe you have to allow the doktype of the mounted pages `plugin.tx_csseo.sitemap.pages.doktypes = 1,7` ?
