### ISSUE TITLE
How to use canonical with multiple detail pages for models?

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#98]
Is there a way to configure `cs_seo` to render a correct canonical tag when multiple detail-pages for the same model exist? For example, we have a model `news` and the `news` records are being rendered on page A as `/news/details-a/my-news-record-title/` and page B  as `/news/details-b/my-news-record-title/`.

When configuring page A to use page B as the canonical target, it doesn't work. The canonical for page A is still `/news/details-a/my-news-record-title/`.

Is there a way to have it render `/news/details-b/my-news-record-title/` for page A?

Thanks!

**Comment by mhirdes** [comment]
Hey. Currently you can set the canocical tag for each news manually. Or you modify the lib.currentUrl.parameter. The problem is that you can't avoid that a news record can be shown on both news detail pages. We always use only one detail page for one domain.

**Comment by mhirdes** [comment]
To modify the lib.currentUrl is maybe the best solution. If you would like to have another and have a sugggestion feel free to reopen the issue again.
