### ISSUE TITLE
Option to configure behavior of canonical URL for mounted pages

### ISSUE THREAD

**Issue by thasmo** [clickstorm/cs_seo#99]
Currently the canonical URL for mounted pages is the same URL as the mounted URL. Consider the following tree:
```
- page M (mounts page X)
- page X
|- page Xa
|- page Xb
```

The canonical URL of the mounted page `Xa` is `/page-m/page-xa/`. It would be useful if it's possible to configure page `M` to render the canonical URL and canonical URLs of the mounted sub-pages to use page `X` as parent page.

The canonical URL of page `Xa` would be `/page-x/page-xa/` then.

I hope my explanation and requirement is understandable. Ideally there would be a SEO tab on page `M` in the backend where I could change the behavior. (So it's possible to change the behavior per mount point.)

**Comment by vmans** [comment]
On issue #16 I added this remark:

'Meanwhile, I found out that parameters like "?MP=5820-6612" get also attached in the navigation.'

This is somewhat related I think. In general, please make all known parameters configurable.

**Comment by mhirdes** [comment]
I think this is a bigger issue. I can't say when I will have the time, to take a look. Pull requests are allways welcome.

**Comment by mhirdes** [comment]
Canonicals are now part of the core https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-20051-SupportTheCanonicalTag.html
